/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface ApiKeyCreateRequest {
    name: string;
    expiresAt?: Date;
}
