# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from .types.message_controller_find_all_request_status import (
    MessageControllerFindAllRequestStatus,
)
from ..core.request_options import RequestOptions
from .types.message_controller_find_all_response import MessageControllerFindAllResponse
from ..core.pydantic_utilities import parse_obj_as
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from .types.message_controller_send_response import MessageControllerSendResponse
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MessageClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def message_controller_find_all(
        self,
        *,
        page: int,
        limit: int,
        status: typing.Optional[MessageControllerFindAllRequestStatus] = None,
        sim_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessageControllerFindAllResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ

        No description provided

        Parameters
        ----------
        page : int

        limit : int

        status : typing.Optional[MessageControllerFindAllRequestStatus]

        sim_id : typing.Optional[str]

        search : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageControllerFindAllResponse


        Examples
        --------
        from unlimited_messaging import UnlimitedMessagingApi

        client = UnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )
        client.message.message_controller_find_all(
            page=1,
            limit=1,
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "message",
            method="GET",
            params={
                "page": page,
                "limit": limit,
                "status": status,
                "simId": sim_id,
                "search": search,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MessageControllerFindAllResponse,
                    parse_obj_as(
                        type_=MessageControllerFindAllResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def message_controller_send(
        self,
        *,
        recipient: str,
        text: str,
        sim_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessageControllerSendResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:WRITE

        No description provided

        Parameters
        ----------
        recipient : str

        text : str

        sim_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageControllerSendResponse


        Examples
        --------
        from unlimited_messaging import UnlimitedMessagingApi

        client = UnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )
        client.message.message_controller_send(
            recipient="recipient",
            text="text",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "message",
            method="POST",
            json={
                "recipient": recipient,
                "text": text,
                "simId": sim_id,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MessageControllerSendResponse,
                    parse_obj_as(
                        type_=MessageControllerSendResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncMessageClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def message_controller_find_all(
        self,
        *,
        page: int,
        limit: int,
        status: typing.Optional[MessageControllerFindAllRequestStatus] = None,
        sim_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessageControllerFindAllResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ

        No description provided

        Parameters
        ----------
        page : int

        limit : int

        status : typing.Optional[MessageControllerFindAllRequestStatus]

        sim_id : typing.Optional[str]

        search : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageControllerFindAllResponse


        Examples
        --------
        import asyncio

        from unlimited_messaging import AsyncUnlimitedMessagingApi

        client = AsyncUnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.message.message_controller_find_all(
                page=1,
                limit=1,
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "message",
            method="GET",
            params={
                "page": page,
                "limit": limit,
                "status": status,
                "simId": sim_id,
                "search": search,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MessageControllerFindAllResponse,
                    parse_obj_as(
                        type_=MessageControllerFindAllResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def message_controller_send(
        self,
        *,
        recipient: str,
        text: str,
        sim_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessageControllerSendResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:WRITE

        No description provided

        Parameters
        ----------
        recipient : str

        text : str

        sim_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageControllerSendResponse


        Examples
        --------
        import asyncio

        from unlimited_messaging import AsyncUnlimitedMessagingApi

        client = AsyncUnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.message.message_controller_send(
                recipient="recipient",
                text="text",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "message",
            method="POST",
            json={
                "recipient": recipient,
                "text": text,
                "simId": sim_id,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MessageControllerSendResponse,
                    parse_obj_as(
                        type_=MessageControllerSendResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
