/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as UnlimitedMessagingApi from "../../../index";
export declare namespace Message {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Message {
    protected readonly _options: Message.Options;
    constructor(_options: Message.Options);
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ
     *
     * No description provided
     *
     * @param {UnlimitedMessagingApi.MessageControllerFindAllRequest} request
     * @param {Message.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.message.messageControllerFindAll({
     *         page: 1,
     *         limit: 1
     *     })
     */
    messageControllerFindAll(request: UnlimitedMessagingApi.MessageControllerFindAllRequest, requestOptions?: Message.RequestOptions): core.HttpResponsePromise<UnlimitedMessagingApi.MessageControllerFindAllResponse>;
    private __messageControllerFindAll;
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:WRITE
     *
     * No description provided
     *
     * @param {UnlimitedMessagingApi.MessageControllerSendRequest} request
     * @param {Message.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.message.messageControllerSend({
     *         recipient: "recipient",
     *         text: "text"
     *     })
     */
    messageControllerSend(request: UnlimitedMessagingApi.MessageControllerSendRequest, requestOptions?: Message.RequestOptions): core.HttpResponsePromise<UnlimitedMessagingApi.MessageControllerSendResponse>;
    private __messageControllerSend;
    protected _getAuthorizationHeader(): Promise<string>;
}
