# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from .types.message_find_all_request_channel import MessageFindAllRequestChannel
from .types.message_find_all_request_status import MessageFindAllRequestStatus
from .types.message_find_all_request_direction import MessageFindAllRequestDirection
from ..core.request_options import RequestOptions
from .types.message_find_all_response import MessageFindAllResponse
from ..core.pydantic_utilities import parse_obj_as
from ..errors.bad_request_error import BadRequestError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.forbidden_error import ForbiddenError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from .types.message_send_response import MessageSendResponse
from ..errors.not_found_error import NotFoundError
from ..errors.conflict_error import ConflictError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from .types.message_find_one_response import MessageFindOneResponse
from ..core.jsonable_encoder import jsonable_encoder
from .types.message_get_status_history_response import MessageGetStatusHistoryResponse
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MessagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def message_find_all(
        self,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        channel: typing.Optional[MessageFindAllRequestChannel] = None,
        status: typing.Optional[MessageFindAllRequestStatus] = None,
        direction: typing.Optional[MessageFindAllRequestDirection] = None,
        messaging_account_id: typing.Optional[str] = None,
        sim_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessageFindAllResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ

        Returns a paginated list of messages for the authenticated user. Supports filtering by `status`, `messagingAccountId`, and free-text `search`. Results are ordered by creation date (most recent first). Use `page` (default 1) and `limit` (1-100, default 20) to paginate. `simId` is a deprecated alias for `messagingAccountId`, removed 2026-12-16.

        Parameters
        ----------
        page : typing.Optional[int]

        limit : typing.Optional[int]

        channel : typing.Optional[MessageFindAllRequestChannel]

        status : typing.Optional[MessageFindAllRequestStatus]

        direction : typing.Optional[MessageFindAllRequestDirection]

        messaging_account_id : typing.Optional[str]

        sim_id : typing.Optional[str]

        search : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageFindAllResponse


        Examples
        --------
        from unlimited_messaging import UnlimitedMessagingApi

        client = UnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )
        client.messages.message_find_all()
        """
        _response = self._client_wrapper.httpx_client.request(
            "message",
            method="GET",
            params={
                "page": page,
                "limit": limit,
                "channel": channel,
                "status": status,
                "direction": direction,
                "messagingAccountId": messaging_account_id,
                "simId": sim_id,
                "search": search,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MessageFindAllResponse,
                    parse_obj_as(
                        type_=MessageFindAllResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def message_send(
        self,
        *,
        text: str,
        recipient: typing.Optional[str] = OMIT,
        account_id: typing.Optional[str] = OMIT,
        sim_id: typing.Optional[str] = OMIT,
        reply_to_message_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessageSendResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:WRITE

        Queues a WhatsApp message for delivery to the specified `recipient`: a phone number (E.164 format) for a 1:1 chat, or a WhatsApp group id (numeric, with or without its `@g.us` suffix) to address a group directly. If `accountId` is omitted, the platform resolves an account automatically using this priority order: (1) if the caller has exactly one active account, it is used; (2) if the caller has no account, the shared system account is used as fallback; (3) if the caller has multiple active accounts, a `400` is returned asking to specify `accountId`. Returns `404` if no account is available at all. Message text is limited to 1 600 characters. Provide `replyToMessageId` instead of `recipient` to send a quoted reply to a message already in the account's history: the conversation (a group included) and the account used are both derived from that message, and `accountId` is ignored. Beta (whatsmeow) WhatsApp accounts only for now. `simId` is a deprecated alias for `accountId`, removed 2026-12-16.

        Parameters
        ----------
        text : str

        recipient : typing.Optional[str]

        account_id : typing.Optional[str]

        sim_id : typing.Optional[str]

        reply_to_message_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageSendResponse


        Examples
        --------
        from unlimited_messaging import UnlimitedMessagingApi

        client = UnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )
        client.messages.message_send(
            text="text",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "message",
            method="POST",
            json={
                "recipient": recipient,
                "text": text,
                "accountId": account_id,
                "simId": sim_id,
                "replyToMessageId": reply_to_message_id,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MessageSendResponse,
                    parse_obj_as(
                        type_=MessageSendResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 409:
                raise ConflictError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def message_find_one(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageFindOneResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ

        Returns a single message by its unique identifier. Returns 404 if the message is not found or does not belong to the authenticated user.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageFindOneResponse


        Examples
        --------
        from unlimited_messaging import UnlimitedMessagingApi

        client = UnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )
        client.messages.message_find_one(
            id="id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"message/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MessageFindOneResponse,
                    parse_obj_as(
                        type_=MessageFindOneResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def message_get_status_history(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageGetStatusHistoryResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ

        Returns every recorded status event per channel for a message owned by the authenticated user, flagging which ones advanced the denormalized current status (out-of-order acks stay non-effective). Returns 404 if the message is not found or does not belong to the authenticated user.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageGetStatusHistoryResponse


        Examples
        --------
        from unlimited_messaging import UnlimitedMessagingApi

        client = UnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )
        client.messages.message_get_status_history(
            id="id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"message/{jsonable_encoder(id)}/status-history",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MessageGetStatusHistoryResponse,
                    parse_obj_as(
                        type_=MessageGetStatusHistoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncMessagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def message_find_all(
        self,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        channel: typing.Optional[MessageFindAllRequestChannel] = None,
        status: typing.Optional[MessageFindAllRequestStatus] = None,
        direction: typing.Optional[MessageFindAllRequestDirection] = None,
        messaging_account_id: typing.Optional[str] = None,
        sim_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessageFindAllResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ

        Returns a paginated list of messages for the authenticated user. Supports filtering by `status`, `messagingAccountId`, and free-text `search`. Results are ordered by creation date (most recent first). Use `page` (default 1) and `limit` (1-100, default 20) to paginate. `simId` is a deprecated alias for `messagingAccountId`, removed 2026-12-16.

        Parameters
        ----------
        page : typing.Optional[int]

        limit : typing.Optional[int]

        channel : typing.Optional[MessageFindAllRequestChannel]

        status : typing.Optional[MessageFindAllRequestStatus]

        direction : typing.Optional[MessageFindAllRequestDirection]

        messaging_account_id : typing.Optional[str]

        sim_id : typing.Optional[str]

        search : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageFindAllResponse


        Examples
        --------
        import asyncio

        from unlimited_messaging import AsyncUnlimitedMessagingApi

        client = AsyncUnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.messages.message_find_all()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "message",
            method="GET",
            params={
                "page": page,
                "limit": limit,
                "channel": channel,
                "status": status,
                "direction": direction,
                "messagingAccountId": messaging_account_id,
                "simId": sim_id,
                "search": search,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MessageFindAllResponse,
                    parse_obj_as(
                        type_=MessageFindAllResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def message_send(
        self,
        *,
        text: str,
        recipient: typing.Optional[str] = OMIT,
        account_id: typing.Optional[str] = OMIT,
        sim_id: typing.Optional[str] = OMIT,
        reply_to_message_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessageSendResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:WRITE

        Queues a WhatsApp message for delivery to the specified `recipient`: a phone number (E.164 format) for a 1:1 chat, or a WhatsApp group id (numeric, with or without its `@g.us` suffix) to address a group directly. If `accountId` is omitted, the platform resolves an account automatically using this priority order: (1) if the caller has exactly one active account, it is used; (2) if the caller has no account, the shared system account is used as fallback; (3) if the caller has multiple active accounts, a `400` is returned asking to specify `accountId`. Returns `404` if no account is available at all. Message text is limited to 1 600 characters. Provide `replyToMessageId` instead of `recipient` to send a quoted reply to a message already in the account's history: the conversation (a group included) and the account used are both derived from that message, and `accountId` is ignored. Beta (whatsmeow) WhatsApp accounts only for now. `simId` is a deprecated alias for `accountId`, removed 2026-12-16.

        Parameters
        ----------
        text : str

        recipient : typing.Optional[str]

        account_id : typing.Optional[str]

        sim_id : typing.Optional[str]

        reply_to_message_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageSendResponse


        Examples
        --------
        import asyncio

        from unlimited_messaging import AsyncUnlimitedMessagingApi

        client = AsyncUnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.messages.message_send(
                text="text",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "message",
            method="POST",
            json={
                "recipient": recipient,
                "text": text,
                "accountId": account_id,
                "simId": sim_id,
                "replyToMessageId": reply_to_message_id,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MessageSendResponse,
                    parse_obj_as(
                        type_=MessageSendResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 409:
                raise ConflictError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def message_find_one(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageFindOneResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ

        Returns a single message by its unique identifier. Returns 404 if the message is not found or does not belong to the authenticated user.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageFindOneResponse


        Examples
        --------
        import asyncio

        from unlimited_messaging import AsyncUnlimitedMessagingApi

        client = AsyncUnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.messages.message_find_one(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"message/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MessageFindOneResponse,
                    parse_obj_as(
                        type_=MessageFindOneResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def message_get_status_history(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageGetStatusHistoryResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ

        Returns every recorded status event per channel for a message owned by the authenticated user, flagging which ones advanced the denormalized current status (out-of-order acks stay non-effective). Returns 404 if the message is not found or does not belong to the authenticated user.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageGetStatusHistoryResponse


        Examples
        --------
        import asyncio

        from unlimited_messaging import AsyncUnlimitedMessagingApi

        client = AsyncUnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.messages.message_get_status_history(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"message/{jsonable_encoder(id)}/status-history",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MessageGetStatusHistoryResponse,
                    parse_obj_as(
                        type_=MessageGetStatusHistoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
