/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageControllerFindAllResponseDataItemDirection: core.serialization.Schema<serializers.MessageControllerFindAllResponseDataItemDirection.Raw, UnlimitedMessagingApi.MessageControllerFindAllResponseDataItemDirection>;
export declare namespace MessageControllerFindAllResponseDataItemDirection {
    type Raw = "IN" | "OUT";
}
