/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
import { WebhookEventMessageHistoryDataChannelType } from "./WebhookEventMessageHistoryDataChannelType";
import { WebhookEventMessageHistoryDataChannelAccount } from "./WebhookEventMessageHistoryDataChannelAccount";
export declare const WebhookEventMessageHistoryDataChannel: core.serialization.ObjectSchema<serializers.WebhookEventMessageHistoryDataChannel.Raw, UnlimitedMessagingApi.WebhookEventMessageHistoryDataChannel>;
export declare namespace WebhookEventMessageHistoryDataChannel {
    interface Raw {
        type: WebhookEventMessageHistoryDataChannelType.Raw;
        account: WebhookEventMessageHistoryDataChannelAccount.Raw;
    }
}
