"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebhookEventMessageSelfSentDataMessage = void 0;
const core = __importStar(require("../../core"));
const WebhookEventMessageSelfSentDataMessageDirection_1 = require("./WebhookEventMessageSelfSentDataMessageDirection");
const WebhookEventMessageSelfSentDataMessageReplyTo_1 = require("./WebhookEventMessageSelfSentDataMessageReplyTo");
exports.WebhookEventMessageSelfSentDataMessage = core.serialization.object({
    id: core.serialization.string(),
    externalId: core.serialization.string().nullable(),
    direction: WebhookEventMessageSelfSentDataMessageDirection_1.WebhookEventMessageSelfSentDataMessageDirection,
    fromMe: core.serialization.boolean(),
    content: core.serialization.string().nullable(),
    sentAt: core.serialization.date(),
    receivedAt: core.serialization.date(),
    sender: core.serialization.string().nullable(),
    senderId: core.serialization.string(),
    senderName: core.serialization.string().nullable(),
    participant: core.serialization.string().nullable(),
    replyTo: WebhookEventMessageSelfSentDataMessageReplyTo_1.WebhookEventMessageSelfSentDataMessageReplyTo.nullable(),
    mediaUrl: core.serialization.string().optional(),
    mediaType: core.serialization.string().optional(),
    mimeType: core.serialization.string().optional(),
    mediaFilename: core.serialization.string().optional(),
    mediaSize: core.serialization.number().optional(),
    durationSec: core.serialization.number().optional(),
    mediaError: core.serialization.string().optional(),
    transcript: core.serialization.string().nullable(),
});
