/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
export declare const WebhookEventGroupUpdatedType: core.serialization.Schema<serializers.WebhookEventGroupUpdatedType.Raw, UnlimitedMessagingApi.WebhookEventGroupUpdatedType>;
export declare namespace WebhookEventGroupUpdatedType {
    type Raw = "group.updated";
}
