/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
export declare const WebhookEventMessageReactionDataChannelType: core.serialization.Schema<serializers.WebhookEventMessageReactionDataChannelType.Raw, UnlimitedMessagingApi.WebhookEventMessageReactionDataChannelType>;
export declare namespace WebhookEventMessageReactionDataChannelType {
    type Raw = "WHATSAPP" | "SMS" | "EMAIL";
}
