/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
import { WebhookEventMessageEditedDataEdit } from "./WebhookEventMessageEditedDataEdit";
import { WebhookEventMessageEditedDataChannel } from "./WebhookEventMessageEditedDataChannel";
export declare const WebhookEventMessageEditedData: core.serialization.ObjectSchema<serializers.WebhookEventMessageEditedData.Raw, UnlimitedMessagingApi.WebhookEventMessageEditedData>;
export declare namespace WebhookEventMessageEditedData {
    interface Raw {
        edit: WebhookEventMessageEditedDataEdit.Raw;
        channel: WebhookEventMessageEditedDataChannel.Raw;
    }
}
