/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
export declare const WebhookEventMessageSelfSentDataMessageReplyTo: core.serialization.ObjectSchema<serializers.WebhookEventMessageSelfSentDataMessageReplyTo.Raw, UnlimitedMessagingApi.WebhookEventMessageSelfSentDataMessageReplyTo>;
export declare namespace WebhookEventMessageSelfSentDataMessageReplyTo {
    interface Raw {
        externalId: string;
        participant: string | null;
    }
}
