/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
export declare const WebhookEventMessageSelfSentDataChannelConversation: core.serialization.ObjectSchema<serializers.WebhookEventMessageSelfSentDataChannelConversation.Raw, UnlimitedMessagingApi.WebhookEventMessageSelfSentDataChannelConversation>;
export declare namespace WebhookEventMessageSelfSentDataChannelConversation {
    interface Raw {
        id: string | null;
        isGroup: boolean;
        address: string | null;
        participants?: string[] | null;
    }
}
