/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
export declare const WebhookEventMessageReactionDataReaction: core.serialization.ObjectSchema<serializers.WebhookEventMessageReactionDataReaction.Raw, UnlimitedMessagingApi.WebhookEventMessageReactionDataReaction>;
export declare namespace WebhookEventMessageReactionDataReaction {
    interface Raw {
        emoji: string;
        removed: boolean;
        reactedToExternalId: string;
        reactedToMessageId: string | null;
        sender: string | null;
        senderId: string;
        senderName: string | null;
        participant: string | null;
        fromMe: boolean;
        sentAt: string;
    }
}
