/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
import { WebhookEventMessageReceivedDataMessageDirection } from "./WebhookEventMessageReceivedDataMessageDirection";
import { WebhookEventMessageReceivedDataMessageReplyTo } from "./WebhookEventMessageReceivedDataMessageReplyTo";
export declare const WebhookEventMessageReceivedDataMessage: core.serialization.ObjectSchema<serializers.WebhookEventMessageReceivedDataMessage.Raw, UnlimitedMessagingApi.WebhookEventMessageReceivedDataMessage>;
export declare namespace WebhookEventMessageReceivedDataMessage {
    interface Raw {
        id: string;
        externalId: string | null;
        direction: WebhookEventMessageReceivedDataMessageDirection.Raw;
        fromMe: boolean;
        content: string | null;
        sentAt: string;
        receivedAt: string;
        sender: string | null;
        senderId: string;
        senderName: string | null;
        participant: string | null;
        replyTo: WebhookEventMessageReceivedDataMessageReplyTo.Raw | null;
        mediaUrl?: string | null;
        mediaType?: string | null;
        mimeType?: string | null;
        mediaFilename?: string | null;
        mediaSize?: number | null;
        durationSec?: number | null;
        mediaError?: string | null;
        transcript: string | null;
    }
}
