/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
import { WebhookEventMessageHistoryDataMessagesItemDirection } from "./WebhookEventMessageHistoryDataMessagesItemDirection";
import { WebhookEventMessageHistoryDataMessagesItemReplyTo } from "./WebhookEventMessageHistoryDataMessagesItemReplyTo";
import { WebhookEventMessageHistoryDataMessagesItemAttachmentsItem } from "./WebhookEventMessageHistoryDataMessagesItemAttachmentsItem";
import { WebhookEventMessageHistoryDataMessagesItemConversation } from "./WebhookEventMessageHistoryDataMessagesItemConversation";
export declare const WebhookEventMessageHistoryDataMessagesItem: core.serialization.ObjectSchema<serializers.WebhookEventMessageHistoryDataMessagesItem.Raw, UnlimitedMessagingApi.WebhookEventMessageHistoryDataMessagesItem>;
export declare namespace WebhookEventMessageHistoryDataMessagesItem {
    interface Raw {
        id: string;
        externalId: string | null;
        direction: WebhookEventMessageHistoryDataMessagesItemDirection.Raw;
        fromMe: boolean;
        content: string | null;
        sentAt: string;
        receivedAt: string;
        sender: string | null;
        senderId: string;
        senderName: string | null;
        participant: string | null;
        replyTo: WebhookEventMessageHistoryDataMessagesItemReplyTo.Raw | null;
        mediaUrl?: string | null;
        mediaType?: string | null;
        mimeType?: string | null;
        mediaFilename?: string | null;
        mediaSize?: number | null;
        durationSec?: number | null;
        mediaError?: string | null;
        transcript: string | null;
        subject?: string | null;
        html?: string | null;
        attachments?: WebhookEventMessageHistoryDataMessagesItemAttachmentsItem.Raw[] | null;
        conversation: WebhookEventMessageHistoryDataMessagesItemConversation.Raw;
    }
}
