/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
export declare const WebhookEventMessageEditedDataEditError: core.serialization.Schema<serializers.WebhookEventMessageEditedDataEditError.Raw, UnlimitedMessagingApi.WebhookEventMessageEditedDataEditError>;
export declare namespace WebhookEventMessageEditedDataEditError {
    type Raw = "original_secret_missing" | "decryption_failed";
}
