/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
import { WebhookEventAccountStatusChangedDataAccountStatus } from "./WebhookEventAccountStatusChangedDataAccountStatus";
import { WebhookEventAccountStatusChangedDataAccountPreviousStatus } from "./WebhookEventAccountStatusChangedDataAccountPreviousStatus";
export declare const WebhookEventAccountStatusChangedDataAccount: core.serialization.ObjectSchema<serializers.WebhookEventAccountStatusChangedDataAccount.Raw, UnlimitedMessagingApi.WebhookEventAccountStatusChangedDataAccount>;
export declare namespace WebhookEventAccountStatusChangedDataAccount {
    interface Raw {
        id: string;
        name: string | null;
        status: WebhookEventAccountStatusChangedDataAccountStatus.Raw;
        previousStatus: WebhookEventAccountStatusChangedDataAccountPreviousStatus.Raw | null;
        reason: string | null;
        transportCode: number | null;
        blockedUntil: string | null;
        at: string;
    }
}
