/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
export declare const WebhookEventMessageEditedDataChannelAccount: core.serialization.ObjectSchema<serializers.WebhookEventMessageEditedDataChannelAccount.Raw, UnlimitedMessagingApi.WebhookEventMessageEditedDataChannelAccount>;
export declare namespace WebhookEventMessageEditedDataChannelAccount {
    interface Raw {
        id: string;
        name: string | null;
    }
}
