/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
import { WebhookEventMessageStatusDataChannelType } from "./WebhookEventMessageStatusDataChannelType";
import { WebhookEventMessageStatusDataChannelAccount } from "./WebhookEventMessageStatusDataChannelAccount";
import { WebhookEventMessageStatusDataChannelConversation } from "./WebhookEventMessageStatusDataChannelConversation";
export declare const WebhookEventMessageStatusDataChannel: core.serialization.ObjectSchema<serializers.WebhookEventMessageStatusDataChannel.Raw, UnlimitedMessagingApi.WebhookEventMessageStatusDataChannel>;
export declare namespace WebhookEventMessageStatusDataChannel {
    interface Raw {
        type: WebhookEventMessageStatusDataChannelType.Raw;
        account: WebhookEventMessageStatusDataChannelAccount.Raw;
        conversation: WebhookEventMessageStatusDataChannelConversation.Raw;
    }
}
