/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
import { WebhookEventMessageHistoryType } from "./WebhookEventMessageHistoryType";
import { WebhookEventMessageHistoryData } from "./WebhookEventMessageHistoryData";
export declare const WebhookEventMessageHistory: core.serialization.ObjectSchema<serializers.WebhookEventMessageHistory.Raw, UnlimitedMessagingApi.WebhookEventMessageHistory>;
export declare namespace WebhookEventMessageHistory {
    interface Raw {
        type: WebhookEventMessageHistoryType.Raw;
        eventId: string;
        occurredAt: string;
        data: WebhookEventMessageHistoryData.Raw;
    }
}
