/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
export declare const WebhookEventMessageDeletedDataDeletion: core.serialization.ObjectSchema<serializers.WebhookEventMessageDeletedDataDeletion.Raw, UnlimitedMessagingApi.WebhookEventMessageDeletedDataDeletion>;
export declare namespace WebhookEventMessageDeletedDataDeletion {
    interface Raw {
        externalId: string;
        messageId: string | null;
        deletedAt: string;
        deletedBy: string | null;
        deletedById: string;
        participant: string | null;
        fromMe: boolean;
    }
}
