/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
export declare const WebhookEventMessageHistoryDataMessagesItemConversation: core.serialization.ObjectSchema<serializers.WebhookEventMessageHistoryDataMessagesItemConversation.Raw, UnlimitedMessagingApi.WebhookEventMessageHistoryDataMessagesItemConversation>;
export declare namespace WebhookEventMessageHistoryDataMessagesItemConversation {
    interface Raw {
        id: string | null;
        isGroup: boolean;
        address: string | null;
        participants?: string[] | null;
    }
}
