/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
export declare const WebhookEventGroupUpdatedDataChannelType: core.serialization.Schema<serializers.WebhookEventGroupUpdatedDataChannelType.Raw, UnlimitedMessagingApi.WebhookEventGroupUpdatedDataChannelType>;
export declare namespace WebhookEventGroupUpdatedDataChannelType {
    type Raw = "WHATSAPP" | "SMS" | "EMAIL";
}
