/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
import { WebhookEventMessageStatusType } from "./WebhookEventMessageStatusType";
import { WebhookEventMessageStatusData } from "./WebhookEventMessageStatusData";
export declare const WebhookEventMessageStatus: core.serialization.ObjectSchema<serializers.WebhookEventMessageStatus.Raw, UnlimitedMessagingApi.WebhookEventMessageStatus>;
export declare namespace WebhookEventMessageStatus {
    interface Raw {
        type: WebhookEventMessageStatusType.Raw;
        eventId: string;
        occurredAt: string;
        data: WebhookEventMessageStatusData.Raw;
    }
}
