/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
export declare const WebhookEventMessageEditedDataChannelType: core.serialization.Schema<serializers.WebhookEventMessageEditedDataChannelType.Raw, UnlimitedMessagingApi.WebhookEventMessageEditedDataChannelType>;
export declare namespace WebhookEventMessageEditedDataChannelType {
    type Raw = "WHATSAPP" | "SMS" | "EMAIL";
}
