/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
export declare const WebhookEventMessageHistoryDataChannelType: core.serialization.Schema<serializers.WebhookEventMessageHistoryDataChannelType.Raw, UnlimitedMessagingApi.WebhookEventMessageHistoryDataChannelType>;
export declare namespace WebhookEventMessageHistoryDataChannelType {
    type Raw = "WHATSAPP" | "SMS" | "EMAIL";
}
