/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
import { WebhookEventAccountStatusChangedDataAccount } from "./WebhookEventAccountStatusChangedDataAccount";
export declare const WebhookEventAccountStatusChangedData: core.serialization.ObjectSchema<serializers.WebhookEventAccountStatusChangedData.Raw, UnlimitedMessagingApi.WebhookEventAccountStatusChangedData>;
export declare namespace WebhookEventAccountStatusChangedData {
    interface Raw {
        account: WebhookEventAccountStatusChangedDataAccount.Raw;
    }
}
