/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as UnlimitedMessagingApi from "../../api/index";
import * as core from "../../core";
import { WebhookEventMessageReceivedDataChannelType } from "./WebhookEventMessageReceivedDataChannelType";
import { WebhookEventMessageReceivedDataChannelAccount } from "./WebhookEventMessageReceivedDataChannelAccount";
import { WebhookEventMessageReceivedDataChannelConversation } from "./WebhookEventMessageReceivedDataChannelConversation";
export declare const WebhookEventMessageReceivedDataChannel: core.serialization.ObjectSchema<serializers.WebhookEventMessageReceivedDataChannel.Raw, UnlimitedMessagingApi.WebhookEventMessageReceivedDataChannel>;
export declare namespace WebhookEventMessageReceivedDataChannel {
    interface Raw {
        type: WebhookEventMessageReceivedDataChannelType.Raw;
        account: WebhookEventMessageReceivedDataChannelAccount.Raw;
        conversation: WebhookEventMessageReceivedDataChannelConversation.Raw;
    }
}
