# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from .types.sim_legacy_get_linked_sims_response_item import (
    SimLegacyGetLinkedSimsResponseItem,
)
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.forbidden_error import ForbiddenError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from .types.sim_legacy_link_sim_response import SimLegacyLinkSimResponse
from ..errors.service_unavailable_error import ServiceUnavailableError
from .types.sim_legacy_get_sim_qr_code_response import SimLegacyGetSimQrCodeResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..errors.not_found_error import NotFoundError
from .types.sim_legacy_get_sim_response import SimLegacyGetSimResponse
from .types.sim_legacy_update_sim_response import SimLegacyUpdateSimResponse
from ..errors.bad_request_error import BadRequestError
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SiMsDeprecatedClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def sim_legacy_get_linked_sims(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SimLegacyGetLinkedSimsResponseItem]:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE

        Deprecated: use GET /account instead, which returns `channel` + `isSystem` in place of `type`. This route is removed on 2026-12-16.

        Returns all active SIM cards linked to the authenticated user's account. Deactivated SIMs are excluded from the response.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SimLegacyGetLinkedSimsResponseItem]


        Examples
        --------
        from unlimited_messaging import UnlimitedMessagingApi

        client = UnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )
        client.si_ms_deprecated.sim_legacy_get_linked_sims()
        """
        _response = self._client_wrapper.httpx_client.request(
            "sim",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.List[SimLegacyGetLinkedSimsResponseItem],
                    parse_obj_as(
                        type_=typing.List[SimLegacyGetLinkedSimsResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def sim_legacy_link_sim(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SimLegacyLinkSimResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE

        Deprecated: use GET /account/link instead, which also lets you pick the `beta` connection method. This route is removed on 2026-12-16 and always links on `stable`.

        Creates a new SIM in Linking status and starts the WhatsApp session. Poll GET /sim/:simId/qrcode every second to get the QR code to scan.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SimLegacyLinkSimResponse


        Examples
        --------
        from unlimited_messaging import UnlimitedMessagingApi

        client = UnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )
        client.si_ms_deprecated.sim_legacy_link_sim()
        """
        _response = self._client_wrapper.httpx_client.request(
            "sim/link",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    SimLegacyLinkSimResponse,
                    parse_obj_as(
                        type_=SimLegacyLinkSimResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def sim_legacy_get_sim_qr_code(
        self, sim_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SimLegacyGetSimQrCodeResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE

        Deprecated: use GET /account/:accountId/challenge instead, which returns a channel-agnostic `challenge` object rather than a WhatsApp-specific `qrCode` string. This route is removed on 2026-12-16.

        Returns the latest QR code for a SIM in Linking status. Poll every second until a QR code is available, then display it. Returns null if the QR is not yet ready.

        Parameters
        ----------
        sim_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SimLegacyGetSimQrCodeResponse


        Examples
        --------
        from unlimited_messaging import UnlimitedMessagingApi

        client = UnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )
        client.si_ms_deprecated.sim_legacy_get_sim_qr_code(
            sim_id="simId",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"sim/{jsonable_encoder(sim_id)}/qrcode",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    SimLegacyGetSimQrCodeResponse,
                    parse_obj_as(
                        type_=SimLegacyGetSimQrCodeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def sim_legacy_get_sim(
        self, sim_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SimLegacyGetSimResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE

        Deprecated: use GET /account/:accountId instead, which returns `channel` + `isSystem` in place of `type`. This route is removed on 2026-12-16.

        Returns the current state of a SIM including its status. Use this to poll during the linking flow (LINKING -> ACTIVE).

        Parameters
        ----------
        sim_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SimLegacyGetSimResponse


        Examples
        --------
        from unlimited_messaging import UnlimitedMessagingApi

        client = UnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )
        client.si_ms_deprecated.sim_legacy_get_sim(
            sim_id="simId",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"sim/{jsonable_encoder(sim_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    SimLegacyGetSimResponse,
                    parse_obj_as(
                        type_=SimLegacyGetSimResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def sim_legacy_unlink_sim(
        self, sim_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE

        Deprecated: use DELETE /account/:accountId instead. This route is removed on 2026-12-16.

        Disconnects and permanently deactivates a linked SIM. The associated WhatsApp session is terminated.

        Parameters
        ----------
        sim_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from unlimited_messaging import UnlimitedMessagingApi

        client = UnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )
        client.si_ms_deprecated.sim_legacy_unlink_sim(
            sim_id="simId",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"sim/{jsonable_encoder(sim_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def sim_legacy_update_sim(
        self,
        sim_id: str,
        *,
        name: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SimLegacyUpdateSimResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE

        Deprecated: use PATCH /account/:accountId instead. This route is removed on 2026-12-16.

        Updates the custom display name of a linked SIM card.

        Parameters
        ----------
        sim_id : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SimLegacyUpdateSimResponse


        Examples
        --------
        from unlimited_messaging import UnlimitedMessagingApi

        client = UnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )
        client.si_ms_deprecated.sim_legacy_update_sim(
            sim_id="simId",
            name="name",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"sim/{jsonable_encoder(sim_id)}",
            method="PATCH",
            json={
                "name": name,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    SimLegacyUpdateSimResponse,
                    parse_obj_as(
                        type_=SimLegacyUpdateSimResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncSiMsDeprecatedClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def sim_legacy_get_linked_sims(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SimLegacyGetLinkedSimsResponseItem]:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE

        Deprecated: use GET /account instead, which returns `channel` + `isSystem` in place of `type`. This route is removed on 2026-12-16.

        Returns all active SIM cards linked to the authenticated user's account. Deactivated SIMs are excluded from the response.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SimLegacyGetLinkedSimsResponseItem]


        Examples
        --------
        import asyncio

        from unlimited_messaging import AsyncUnlimitedMessagingApi

        client = AsyncUnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.si_ms_deprecated.sim_legacy_get_linked_sims()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "sim",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.List[SimLegacyGetLinkedSimsResponseItem],
                    parse_obj_as(
                        type_=typing.List[SimLegacyGetLinkedSimsResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def sim_legacy_link_sim(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SimLegacyLinkSimResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE

        Deprecated: use GET /account/link instead, which also lets you pick the `beta` connection method. This route is removed on 2026-12-16 and always links on `stable`.

        Creates a new SIM in Linking status and starts the WhatsApp session. Poll GET /sim/:simId/qrcode every second to get the QR code to scan.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SimLegacyLinkSimResponse


        Examples
        --------
        import asyncio

        from unlimited_messaging import AsyncUnlimitedMessagingApi

        client = AsyncUnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.si_ms_deprecated.sim_legacy_link_sim()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "sim/link",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    SimLegacyLinkSimResponse,
                    parse_obj_as(
                        type_=SimLegacyLinkSimResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def sim_legacy_get_sim_qr_code(
        self, sim_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SimLegacyGetSimQrCodeResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE

        Deprecated: use GET /account/:accountId/challenge instead, which returns a channel-agnostic `challenge` object rather than a WhatsApp-specific `qrCode` string. This route is removed on 2026-12-16.

        Returns the latest QR code for a SIM in Linking status. Poll every second until a QR code is available, then display it. Returns null if the QR is not yet ready.

        Parameters
        ----------
        sim_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SimLegacyGetSimQrCodeResponse


        Examples
        --------
        import asyncio

        from unlimited_messaging import AsyncUnlimitedMessagingApi

        client = AsyncUnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.si_ms_deprecated.sim_legacy_get_sim_qr_code(
                sim_id="simId",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"sim/{jsonable_encoder(sim_id)}/qrcode",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    SimLegacyGetSimQrCodeResponse,
                    parse_obj_as(
                        type_=SimLegacyGetSimQrCodeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def sim_legacy_get_sim(
        self, sim_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SimLegacyGetSimResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE

        Deprecated: use GET /account/:accountId instead, which returns `channel` + `isSystem` in place of `type`. This route is removed on 2026-12-16.

        Returns the current state of a SIM including its status. Use this to poll during the linking flow (LINKING -> ACTIVE).

        Parameters
        ----------
        sim_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SimLegacyGetSimResponse


        Examples
        --------
        import asyncio

        from unlimited_messaging import AsyncUnlimitedMessagingApi

        client = AsyncUnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.si_ms_deprecated.sim_legacy_get_sim(
                sim_id="simId",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"sim/{jsonable_encoder(sim_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    SimLegacyGetSimResponse,
                    parse_obj_as(
                        type_=SimLegacyGetSimResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def sim_legacy_unlink_sim(
        self, sim_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE

        Deprecated: use DELETE /account/:accountId instead. This route is removed on 2026-12-16.

        Disconnects and permanently deactivates a linked SIM. The associated WhatsApp session is terminated.

        Parameters
        ----------
        sim_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from unlimited_messaging import AsyncUnlimitedMessagingApi

        client = AsyncUnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.si_ms_deprecated.sim_legacy_unlink_sim(
                sim_id="simId",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"sim/{jsonable_encoder(sim_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def sim_legacy_update_sim(
        self,
        sim_id: str,
        *,
        name: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SimLegacyUpdateSimResponse:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE

        Deprecated: use PATCH /account/:accountId instead. This route is removed on 2026-12-16.

        Updates the custom display name of a linked SIM card.

        Parameters
        ----------
        sim_id : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SimLegacyUpdateSimResponse


        Examples
        --------
        import asyncio

        from unlimited_messaging import AsyncUnlimitedMessagingApi

        client = AsyncUnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.si_ms_deprecated.sim_legacy_update_sim(
                sim_id="simId",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"sim/{jsonable_encoder(sim_id)}",
            method="PATCH",
            json={
                "name": name,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    SimLegacyUpdateSimResponse,
                    parse_obj_as(
                        type_=SimLegacyUpdateSimResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
