/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
import { SimLegacyGetSimResponseType } from "./SimLegacyGetSimResponseType";
import { SimLegacyGetSimResponseChannel } from "./SimLegacyGetSimResponseChannel";
import { SimLegacyGetSimResponseStatus } from "./SimLegacyGetSimResponseStatus";
export declare const SimLegacyGetSimResponse: core.serialization.ObjectSchema<serializers.SimLegacyGetSimResponse.Raw, UnlimitedMessagingApi.SimLegacyGetSimResponse>;
export declare namespace SimLegacyGetSimResponse {
    interface Raw {
        id: string;
        type: SimLegacyGetSimResponseType.Raw;
        channel: SimLegacyGetSimResponseChannel.Raw;
        isSystem: boolean;
        status: SimLegacyGetSimResponseStatus.Raw;
        phone: string | null;
        name: string | null;
        blockedUntil: string | null;
        createdAt: string;
        updatedAt: string;
    }
}
