/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const SimLegacyGetSimResponseType: core.serialization.Schema<serializers.SimLegacyGetSimResponseType.Raw, UnlimitedMessagingApi.SimLegacyGetSimResponseType>;
export declare namespace SimLegacyGetSimResponseType {
    type Raw = "SYSTEM" | "USER";
}
