/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const SimLegacyGetLinkedSimsResponseItemStatus: core.serialization.Schema<serializers.SimLegacyGetLinkedSimsResponseItemStatus.Raw, UnlimitedMessagingApi.SimLegacyGetLinkedSimsResponseItemStatus>;
export declare namespace SimLegacyGetLinkedSimsResponseItemStatus {
    type Raw = "PENDING" | "ACTIVE" | "INACTIVE" | "LINKING" | "BLOCKED" | "DUPLICATE";
}
