/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const SimLegacyGetLinkedSimsResponseItemChannel: core.serialization.Schema<serializers.SimLegacyGetLinkedSimsResponseItemChannel.Raw, UnlimitedMessagingApi.SimLegacyGetLinkedSimsResponseItemChannel>;
export declare namespace SimLegacyGetLinkedSimsResponseItemChannel {
    type Raw = "WHATSAPP_BAILYES" | "EMAIL" | "SMS" | "WHATSAPP_WHATSMEOW";
}
