/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const SimLegacyUpdateSimResponseChannel: core.serialization.Schema<serializers.SimLegacyUpdateSimResponseChannel.Raw, UnlimitedMessagingApi.SimLegacyUpdateSimResponseChannel>;
export declare namespace SimLegacyUpdateSimResponseChannel {
    type Raw = "WHATSAPP_BAILYES" | "EMAIL" | "SMS" | "WHATSAPP_WHATSMEOW";
}
