/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const SimLegacyUpdateSimResponseType: core.serialization.Schema<serializers.SimLegacyUpdateSimResponseType.Raw, UnlimitedMessagingApi.SimLegacyUpdateSimResponseType>;
export declare namespace SimLegacyUpdateSimResponseType {
    type Raw = "SYSTEM" | "USER";
}
