/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const SimLegacyUpdateSimResponseStatus: core.serialization.Schema<serializers.SimLegacyUpdateSimResponseStatus.Raw, UnlimitedMessagingApi.SimLegacyUpdateSimResponseStatus>;
export declare namespace SimLegacyUpdateSimResponseStatus {
    type Raw = "PENDING" | "ACTIVE" | "INACTIVE" | "LINKING" | "BLOCKED" | "DUPLICATE";
}
