/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type WebhookEndpointUpdateResponseEventTypesItem = "message.received";
export declare const WebhookEndpointUpdateResponseEventTypesItem: {
    readonly MessageReceived: "message.received";
};
