/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../../../index";
export interface WebhookEndpointCreateResponse {
    id: string;
    url: string;
    description: string | null;
    secretPrefix: string;
    enabled: boolean;
    eventTypes: UnlimitedMessagingApi.WebhookEndpointCreateResponseEventTypesItem[];
    createdAt: Date;
    updatedAt: Date;
    secret: string;
}
