/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type WebhookEndpointFindOneResponseEventTypesItem = "message.received";
export declare const WebhookEndpointFindOneResponseEventTypesItem: {
    readonly MessageReceived: "message.received";
};
