# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .webhook_event_message_history_data_messages_item_direction import (
    WebhookEventMessageHistoryDataMessagesItemDirection,
)
import datetime as dt
from .webhook_event_message_history_data_messages_item_reply_to import (
    WebhookEventMessageHistoryDataMessagesItemReplyTo,
)
from .webhook_event_message_history_data_messages_item_attachments_item import (
    WebhookEventMessageHistoryDataMessagesItemAttachmentsItem,
)
from .webhook_event_message_history_data_messages_item_conversation import (
    WebhookEventMessageHistoryDataMessagesItemConversation,
)
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class WebhookEventMessageHistoryDataMessagesItem(UniversalBaseModel):
    id: str
    external_id: typing.Optional[str] = pydantic.Field(alias="externalId", default=None)
    direction: WebhookEventMessageHistoryDataMessagesItemDirection
    from_me: bool = pydantic.Field(alias="fromMe")
    content: typing.Optional[str] = None
    sent_at: dt.datetime = pydantic.Field(alias="sentAt")
    received_at: dt.datetime = pydantic.Field(alias="receivedAt")
    sender: typing.Optional[str] = None
    sender_id: str = pydantic.Field(alias="senderId")
    sender_name: typing.Optional[str] = pydantic.Field(alias="senderName", default=None)
    participant: typing.Optional[str] = None
    reply_to: typing.Optional[WebhookEventMessageHistoryDataMessagesItemReplyTo] = (
        pydantic.Field(alias="replyTo", default=None)
    )
    media_url: typing.Optional[str] = pydantic.Field(alias="mediaUrl", default=None)
    media_type: typing.Optional[str] = pydantic.Field(alias="mediaType", default=None)
    mime_type: typing.Optional[str] = pydantic.Field(alias="mimeType", default=None)
    media_filename: typing.Optional[str] = pydantic.Field(
        alias="mediaFilename", default=None
    )
    media_size: typing.Optional[int] = pydantic.Field(alias="mediaSize", default=None)
    duration_sec: typing.Optional[int] = pydantic.Field(
        alias="durationSec", default=None
    )
    media_error: typing.Optional[str] = pydantic.Field(alias="mediaError", default=None)
    transcript: typing.Optional[str] = None
    subject: typing.Optional[str] = None
    html: typing.Optional[str] = None
    attachments: typing.Optional[
        typing.List[WebhookEventMessageHistoryDataMessagesItemAttachmentsItem]
    ] = None
    conversation: WebhookEventMessageHistoryDataMessagesItemConversation

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
