# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .webhook_event_message_received_data_channel_type import (
    WebhookEventMessageReceivedDataChannelType,
)
from .webhook_event_message_received_data_channel_account import (
    WebhookEventMessageReceivedDataChannelAccount,
)
from .webhook_event_message_received_data_channel_conversation import (
    WebhookEventMessageReceivedDataChannelConversation,
)
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class WebhookEventMessageReceivedDataChannel(UniversalBaseModel):
    type: WebhookEventMessageReceivedDataChannelType
    account: WebhookEventMessageReceivedDataChannelAccount
    conversation: WebhookEventMessageReceivedDataChannelConversation

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
