# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .webhook_event_message_received_type import WebhookEventMessageReceivedType
import pydantic
import datetime as dt
from .webhook_event_message_received_data import WebhookEventMessageReceivedData
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class WebhookEventMessageReceived(UniversalBaseModel):
    type: WebhookEventMessageReceivedType
    event_id: str = pydantic.Field(alias="eventId")
    occurred_at: dt.datetime = pydantic.Field(alias="occurredAt")
    data: WebhookEventMessageReceivedData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
