# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class WebhookEventMessageReactionDataReaction(UniversalBaseModel):
    emoji: str
    removed: bool
    reacted_to_external_id: str = pydantic.Field(alias="reactedToExternalId")
    reacted_to_message_id: typing.Optional[str] = pydantic.Field(
        alias="reactedToMessageId", default=None
    )
    sender: typing.Optional[str] = None
    sender_id: str = pydantic.Field(alias="senderId")
    sender_name: typing.Optional[str] = pydantic.Field(alias="senderName", default=None)
    participant: typing.Optional[str] = None
    from_me: bool = pydantic.Field(alias="fromMe")
    sent_at: dt.datetime = pydantic.Field(alias="sentAt")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
