# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .webhook_event_message_status_data_channel_type import (
    WebhookEventMessageStatusDataChannelType,
)
from .webhook_event_message_status_data_channel_account import (
    WebhookEventMessageStatusDataChannelAccount,
)
from .webhook_event_message_status_data_channel_conversation import (
    WebhookEventMessageStatusDataChannelConversation,
)
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class WebhookEventMessageStatusDataChannel(UniversalBaseModel):
    type: WebhookEventMessageStatusDataChannelType
    account: WebhookEventMessageStatusDataChannelAccount
    conversation: WebhookEventMessageStatusDataChannelConversation

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
