# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .webhook_event_message_self_sent_data_channel_type import (
    WebhookEventMessageSelfSentDataChannelType,
)
from .webhook_event_message_self_sent_data_channel_account import (
    WebhookEventMessageSelfSentDataChannelAccount,
)
from .webhook_event_message_self_sent_data_channel_conversation import (
    WebhookEventMessageSelfSentDataChannelConversation,
)
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class WebhookEventMessageSelfSentDataChannel(UniversalBaseModel):
    type: WebhookEventMessageSelfSentDataChannelType
    account: WebhookEventMessageSelfSentDataChannelAccount
    conversation: WebhookEventMessageSelfSentDataChannelConversation

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
