/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const ApiKeyCreateResponse: core.serialization.ObjectSchema<serializers.ApiKeyCreateResponse.Raw, UnlimitedMessagingApi.ApiKeyCreateResponse>;
export declare namespace ApiKeyCreateResponse {
    interface Raw {
        id: string;
        name: string;
        prefix: string;
        expiresAt: string | null;
        lastUsedAt: string | null;
        revokedAt: string | null;
        createdAt: string;
        updatedAt: string;
        key: string;
    }
}
