"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Accounts = void 0;
const environments = __importStar(require("../../../../environments"));
const core = __importStar(require("../../../../core"));
const UnlimitedMessagingApi = __importStar(require("../../../index"));
const url_join_1 = __importDefault(require("url-join"));
const serializers = __importStar(require("../../../../serialization/index"));
const errors = __importStar(require("../../../../errors/index"));
class Accounts {
    constructor(_options) {
        this._options = _options;
    }
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE
     *
     * Returns all active messaging accounts linked to the authenticated user's account. Deactivated accounts are excluded from the response.
     *
     * @param {Accounts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link UnlimitedMessagingApi.UnauthorizedError}
     * @throws {@link UnlimitedMessagingApi.ForbiddenError}
     *
     * @example
     *     await client.accounts.accountListAccounts()
     */
    accountListAccounts(requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__accountListAccounts(requestOptions));
    }
    __accountListAccounts(requestOptions) {
        return __awaiter(this, void 0, void 0, function* () {
            var _a, _b;
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.UnlimitedMessagingApiEnvironment.Production, "account"),
                method: "GET",
                headers: Object.assign({ Authorization: yield this._getAuthorizationHeader(), "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                requestType: "json",
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                withCredentials: true,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return {
                    data: serializers.accounts.accountListAccounts.Response.parseOrThrow(_response.body, {
                        unrecognizedObjectKeys: "passthrough",
                        allowUnrecognizedUnionMembers: true,
                        allowUnrecognizedEnumValues: true,
                        breadcrumbsPrefix: ["response"],
                    }),
                    rawResponse: _response.rawResponse,
                };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 401:
                        throw new UnlimitedMessagingApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 403:
                        throw new UnlimitedMessagingApi.ForbiddenError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.UnlimitedMessagingApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.UnlimitedMessagingApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.UnlimitedMessagingApiTimeoutError("Timeout exceeded when calling GET /account.");
                case "unknown":
                    throw new errors.UnlimitedMessagingApiError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE
     *
     * Creates a new account in Linking status and starts a WhatsApp session. Poll GET /account/:accountId/challenge every second to get the QR code to scan. `mode` picks the connection method: `stable` (default) is the long-standing one, `beta` is newer and keeps the connection alive noticeably better.
     *
     * @param {UnlimitedMessagingApi.AccountLinkAccountRequest} request
     * @param {Accounts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link UnlimitedMessagingApi.UnauthorizedError}
     * @throws {@link UnlimitedMessagingApi.ForbiddenError}
     * @throws {@link UnlimitedMessagingApi.ServiceUnavailableError}
     *
     * @example
     *     await client.accounts.accountLinkAccount()
     */
    accountLinkAccount(request = {}, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__accountLinkAccount(request, requestOptions));
    }
    __accountLinkAccount() {
        return __awaiter(this, arguments, void 0, function* (request = {}, requestOptions) {
            var _a, _b;
            const { mode } = request;
            const _queryParams = {};
            if (mode != null) {
                _queryParams["mode"] = serializers.AccountLinkAccountRequestMode.jsonOrThrow(mode, {
                    unrecognizedObjectKeys: "strip",
                });
            }
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.UnlimitedMessagingApiEnvironment.Production, "account/link"),
                method: "GET",
                headers: Object.assign({ Authorization: yield this._getAuthorizationHeader(), "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                queryParameters: _queryParams,
                requestType: "json",
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                withCredentials: true,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return {
                    data: serializers.AccountLinkAccountResponse.parseOrThrow(_response.body, {
                        unrecognizedObjectKeys: "passthrough",
                        allowUnrecognizedUnionMembers: true,
                        allowUnrecognizedEnumValues: true,
                        breadcrumbsPrefix: ["response"],
                    }),
                    rawResponse: _response.rawResponse,
                };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 401:
                        throw new UnlimitedMessagingApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 403:
                        throw new UnlimitedMessagingApi.ForbiddenError(_response.error.body, _response.rawResponse);
                    case 503:
                        throw new UnlimitedMessagingApi.ServiceUnavailableError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.UnlimitedMessagingApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.UnlimitedMessagingApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.UnlimitedMessagingApiTimeoutError("Timeout exceeded when calling GET /account/link.");
                case "unknown":
                    throw new errors.UnlimitedMessagingApiError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE
     *
     * Returns whatever the account still needs to finish connecting - a QR code, a short code, a redirect, or nothing for a channel that connects from credentials alone. Poll every second while the account is in Linking status. Returns null once there is nothing left to do.
     *
     * @param {string} accountId
     * @param {UnlimitedMessagingApi.AccountGetChallengeRequest} request
     * @param {Accounts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link UnlimitedMessagingApi.UnauthorizedError}
     * @throws {@link UnlimitedMessagingApi.ForbiddenError}
     * @throws {@link UnlimitedMessagingApi.NotFoundError}
     *
     * @example
     *     await client.accounts.accountGetChallenge("accountId")
     */
    accountGetChallenge(accountId, request = {}, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__accountGetChallenge(accountId, request, requestOptions));
    }
    __accountGetChallenge(accountId_1) {
        return __awaiter(this, arguments, void 0, function* (accountId, request = {}, requestOptions) {
            var _a, _b;
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.UnlimitedMessagingApiEnvironment.Production, `account/${encodeURIComponent(accountId)}/challenge`),
                method: "GET",
                headers: Object.assign({ Authorization: yield this._getAuthorizationHeader(), "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                requestType: "json",
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                withCredentials: true,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return {
                    data: serializers.AccountGetChallengeResponse.parseOrThrow(_response.body, {
                        unrecognizedObjectKeys: "passthrough",
                        allowUnrecognizedUnionMembers: true,
                        allowUnrecognizedEnumValues: true,
                        breadcrumbsPrefix: ["response"],
                    }),
                    rawResponse: _response.rawResponse,
                };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 401:
                        throw new UnlimitedMessagingApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 403:
                        throw new UnlimitedMessagingApi.ForbiddenError(_response.error.body, _response.rawResponse);
                    case 404:
                        throw new UnlimitedMessagingApi.NotFoundError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.UnlimitedMessagingApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.UnlimitedMessagingApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.UnlimitedMessagingApiTimeoutError("Timeout exceeded when calling GET /account/{accountId}/challenge.");
                case "unknown":
                    throw new errors.UnlimitedMessagingApiError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE
     *
     * Deprecated: use GET /account/:accountId/challenge instead, which returns a channel-agnostic `challenge` object rather than a WhatsApp-specific `qrCode` string. This route is removed on 2026-12-16.
     *
     * Returns the latest QR code for an account in Linking status. Poll every second until a QR code is available, then display it. Returns null if the QR is not yet ready.
     *
     * @param {string} accountId
     * @param {UnlimitedMessagingApi.AccountGetQrCodeRequest} request
     * @param {Accounts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link UnlimitedMessagingApi.UnauthorizedError}
     * @throws {@link UnlimitedMessagingApi.ForbiddenError}
     * @throws {@link UnlimitedMessagingApi.NotFoundError}
     *
     * @example
     *     await client.accounts.accountGetQrCode("accountId")
     */
    accountGetQrCode(accountId, request = {}, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__accountGetQrCode(accountId, request, requestOptions));
    }
    __accountGetQrCode(accountId_1) {
        return __awaiter(this, arguments, void 0, function* (accountId, request = {}, requestOptions) {
            var _a, _b;
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.UnlimitedMessagingApiEnvironment.Production, `account/${encodeURIComponent(accountId)}/qrcode`),
                method: "GET",
                headers: Object.assign({ Authorization: yield this._getAuthorizationHeader(), "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                requestType: "json",
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                withCredentials: true,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return {
                    data: serializers.AccountGetQrCodeResponse.parseOrThrow(_response.body, {
                        unrecognizedObjectKeys: "passthrough",
                        allowUnrecognizedUnionMembers: true,
                        allowUnrecognizedEnumValues: true,
                        breadcrumbsPrefix: ["response"],
                    }),
                    rawResponse: _response.rawResponse,
                };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 401:
                        throw new UnlimitedMessagingApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 403:
                        throw new UnlimitedMessagingApi.ForbiddenError(_response.error.body, _response.rawResponse);
                    case 404:
                        throw new UnlimitedMessagingApi.NotFoundError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.UnlimitedMessagingApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.UnlimitedMessagingApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.UnlimitedMessagingApiTimeoutError("Timeout exceeded when calling GET /account/{accountId}/qrcode.");
                case "unknown":
                    throw new errors.UnlimitedMessagingApiError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE
     *
     * Returns the current state of an account including its status. Use this to poll during the linking flow (LINKING -> ACTIVE).
     *
     * @param {string} accountId
     * @param {UnlimitedMessagingApi.AccountGetAccountRequest} request
     * @param {Accounts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link UnlimitedMessagingApi.UnauthorizedError}
     * @throws {@link UnlimitedMessagingApi.ForbiddenError}
     * @throws {@link UnlimitedMessagingApi.NotFoundError}
     *
     * @example
     *     await client.accounts.accountGetAccount("accountId")
     */
    accountGetAccount(accountId, request = {}, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__accountGetAccount(accountId, request, requestOptions));
    }
    __accountGetAccount(accountId_1) {
        return __awaiter(this, arguments, void 0, function* (accountId, request = {}, requestOptions) {
            var _a, _b;
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.UnlimitedMessagingApiEnvironment.Production, `account/${encodeURIComponent(accountId)}`),
                method: "GET",
                headers: Object.assign({ Authorization: yield this._getAuthorizationHeader(), "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                requestType: "json",
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                withCredentials: true,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return {
                    data: serializers.AccountGetAccountResponse.parseOrThrow(_response.body, {
                        unrecognizedObjectKeys: "passthrough",
                        allowUnrecognizedUnionMembers: true,
                        allowUnrecognizedEnumValues: true,
                        breadcrumbsPrefix: ["response"],
                    }),
                    rawResponse: _response.rawResponse,
                };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 401:
                        throw new UnlimitedMessagingApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 403:
                        throw new UnlimitedMessagingApi.ForbiddenError(_response.error.body, _response.rawResponse);
                    case 404:
                        throw new UnlimitedMessagingApi.NotFoundError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.UnlimitedMessagingApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.UnlimitedMessagingApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.UnlimitedMessagingApiTimeoutError("Timeout exceeded when calling GET /account/{accountId}.");
                case "unknown":
                    throw new errors.UnlimitedMessagingApiError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE
     *
     * Disconnects and permanently deactivates a linked account. The associated WhatsApp session is terminated.
     *
     * @param {string} accountId
     * @param {UnlimitedMessagingApi.AccountUnlinkAccountRequest} request
     * @param {Accounts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link UnlimitedMessagingApi.UnauthorizedError}
     * @throws {@link UnlimitedMessagingApi.ForbiddenError}
     * @throws {@link UnlimitedMessagingApi.NotFoundError}
     *
     * @example
     *     await client.accounts.accountUnlinkAccount("accountId")
     */
    accountUnlinkAccount(accountId, request = {}, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__accountUnlinkAccount(accountId, request, requestOptions));
    }
    __accountUnlinkAccount(accountId_1) {
        return __awaiter(this, arguments, void 0, function* (accountId, request = {}, requestOptions) {
            var _a, _b;
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.UnlimitedMessagingApiEnvironment.Production, `account/${encodeURIComponent(accountId)}`),
                method: "DELETE",
                headers: Object.assign({ Authorization: yield this._getAuthorizationHeader(), "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                requestType: "json",
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                withCredentials: true,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return { data: undefined, rawResponse: _response.rawResponse };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 401:
                        throw new UnlimitedMessagingApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 403:
                        throw new UnlimitedMessagingApi.ForbiddenError(_response.error.body, _response.rawResponse);
                    case 404:
                        throw new UnlimitedMessagingApi.NotFoundError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.UnlimitedMessagingApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.UnlimitedMessagingApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.UnlimitedMessagingApiTimeoutError("Timeout exceeded when calling DELETE /account/{accountId}.");
                case "unknown":
                    throw new errors.UnlimitedMessagingApiError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE
     *
     * Updates the custom display name of a linked messaging account.
     *
     * @param {string} accountId
     * @param {UnlimitedMessagingApi.AccountUpdateAccountRequest} request
     * @param {Accounts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link UnlimitedMessagingApi.BadRequestError}
     * @throws {@link UnlimitedMessagingApi.UnauthorizedError}
     * @throws {@link UnlimitedMessagingApi.ForbiddenError}
     * @throws {@link UnlimitedMessagingApi.NotFoundError}
     *
     * @example
     *     await client.accounts.accountUpdateAccount("accountId", {
     *         name: "name"
     *     })
     */
    accountUpdateAccount(accountId, request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__accountUpdateAccount(accountId, request, requestOptions));
    }
    __accountUpdateAccount(accountId, request, requestOptions) {
        return __awaiter(this, void 0, void 0, function* () {
            var _a, _b;
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.UnlimitedMessagingApiEnvironment.Production, `account/${encodeURIComponent(accountId)}`),
                method: "PATCH",
                headers: Object.assign({ Authorization: yield this._getAuthorizationHeader(), "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                requestType: "json",
                body: serializers.AccountUpdateAccountRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                withCredentials: true,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return {
                    data: serializers.AccountUpdateAccountResponse.parseOrThrow(_response.body, {
                        unrecognizedObjectKeys: "passthrough",
                        allowUnrecognizedUnionMembers: true,
                        allowUnrecognizedEnumValues: true,
                        breadcrumbsPrefix: ["response"],
                    }),
                    rawResponse: _response.rawResponse,
                };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 400:
                        throw new UnlimitedMessagingApi.BadRequestError(_response.error.body, _response.rawResponse);
                    case 401:
                        throw new UnlimitedMessagingApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 403:
                        throw new UnlimitedMessagingApi.ForbiddenError(_response.error.body, _response.rawResponse);
                    case 404:
                        throw new UnlimitedMessagingApi.NotFoundError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.UnlimitedMessagingApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.UnlimitedMessagingApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.UnlimitedMessagingApiTimeoutError("Timeout exceeded when calling PATCH /account/{accountId}.");
                case "unknown":
                    throw new errors.UnlimitedMessagingApiError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    _getAuthorizationHeader() {
        return __awaiter(this, void 0, void 0, function* () {
            return `Bearer ${yield core.Supplier.get(this._options.token)}`;
        });
    }
}
exports.Accounts = Accounts;
