/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as UnlimitedMessagingApi from "../../../index";
export declare namespace Messages {
    interface Options {
        environment?: core.Supplier<environments.UnlimitedMessagingApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
/**
 * Send and retrieve WhatsApp messages.
 */
export declare class Messages {
    protected readonly _options: Messages.Options;
    constructor(_options: Messages.Options);
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ
     *
     * Returns a paginated list of messages for the authenticated user. Supports filtering by `status`, `messagingAccountId`, and free-text `search`. Results are ordered by creation date (most recent first). Use `page` (default 1) and `limit` (1-100, default 20) to paginate. `simId` is a deprecated alias for `messagingAccountId`, removed 2026-12-16.
     *
     * @param {UnlimitedMessagingApi.MessageFindAllRequest} request
     * @param {Messages.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link UnlimitedMessagingApi.BadRequestError}
     * @throws {@link UnlimitedMessagingApi.UnauthorizedError}
     * @throws {@link UnlimitedMessagingApi.ForbiddenError}
     *
     * @example
     *     await client.messages.messageFindAll()
     */
    messageFindAll(request?: UnlimitedMessagingApi.MessageFindAllRequest, requestOptions?: Messages.RequestOptions): core.HttpResponsePromise<UnlimitedMessagingApi.MessageFindAllResponse>;
    private __messageFindAll;
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:WRITE
     *
     * Queues a WhatsApp message for delivery to the specified `recipient`: a phone number (E.164 format) for a 1:1 chat, or a WhatsApp group id (numeric, with or without its `@g.us` suffix) to address a group directly. If `accountId` is omitted, the platform resolves an account automatically using this priority order: (1) if the caller has exactly one active account, it is used; (2) if the caller has no account, the shared system account is used as fallback; (3) if the caller has multiple active accounts, a `400` is returned asking to specify `accountId`. Returns `404` if no account is available at all. Message text is limited to 1 600 characters. Provide `replyToMessageId` instead of `recipient` to send a quoted reply to a message already in the account's history: the conversation (a group included) and the account used are both derived from that message, and `accountId` is ignored. Beta (whatsmeow) WhatsApp accounts only for now. `simId` is a deprecated alias for `accountId`, removed 2026-12-16. To send a media file, upload it first with `POST /media` to get a temp URL, then pass that URL as `mediaUrl` with the matching `mediaType` (`image`, `document`, or `audio`) in this body.
     *
     * @param {UnlimitedMessagingApi.MessageSendRequest} request
     * @param {Messages.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link UnlimitedMessagingApi.BadRequestError}
     * @throws {@link UnlimitedMessagingApi.UnauthorizedError}
     * @throws {@link UnlimitedMessagingApi.ForbiddenError}
     * @throws {@link UnlimitedMessagingApi.NotFoundError}
     * @throws {@link UnlimitedMessagingApi.ConflictError}
     * @throws {@link UnlimitedMessagingApi.UnprocessableEntityError}
     *
     * @example
     *     await client.messages.messageSend()
     */
    messageSend(request?: UnlimitedMessagingApi.MessageSendRequest, requestOptions?: Messages.RequestOptions): core.HttpResponsePromise<UnlimitedMessagingApi.MessageSendResponse>;
    private __messageSend;
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ
     *
     * Returns a single message by its unique identifier. Returns 404 if the message is not found or does not belong to the authenticated user.
     *
     * @param {string} id
     * @param {UnlimitedMessagingApi.MessageFindOneRequest} request
     * @param {Messages.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link UnlimitedMessagingApi.UnauthorizedError}
     * @throws {@link UnlimitedMessagingApi.ForbiddenError}
     * @throws {@link UnlimitedMessagingApi.NotFoundError}
     *
     * @example
     *     await client.messages.messageFindOne("id")
     */
    messageFindOne(id: string, request?: UnlimitedMessagingApi.MessageFindOneRequest, requestOptions?: Messages.RequestOptions): core.HttpResponsePromise<UnlimitedMessagingApi.MessageFindOneResponse>;
    private __messageFindOne;
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ
     *
     * Returns every recorded status event per channel for a message owned by the authenticated user, flagging which ones advanced the denormalized current status (out-of-order acks stay non-effective). Returns 404 if the message is not found or does not belong to the authenticated user.
     *
     * @param {string} id
     * @param {UnlimitedMessagingApi.MessageGetStatusHistoryRequest} request
     * @param {Messages.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link UnlimitedMessagingApi.UnauthorizedError}
     * @throws {@link UnlimitedMessagingApi.ForbiddenError}
     * @throws {@link UnlimitedMessagingApi.NotFoundError}
     *
     * @example
     *     await client.messages.messageGetStatusHistory("id")
     */
    messageGetStatusHistory(id: string, request?: UnlimitedMessagingApi.MessageGetStatusHistoryRequest, requestOptions?: Messages.RequestOptions): core.HttpResponsePromise<UnlimitedMessagingApi.MessageGetStatusHistoryResponse>;
    private __messageGetStatusHistory;
    protected _getAuthorizationHeader(): Promise<string>;
}
