"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Messages = void 0;
const environments = __importStar(require("../../../../environments"));
const core = __importStar(require("../../../../core"));
const UnlimitedMessagingApi = __importStar(require("../../../index"));
const serializers = __importStar(require("../../../../serialization/index"));
const url_join_1 = __importDefault(require("url-join"));
const errors = __importStar(require("../../../../errors/index"));
/**
 * Send and retrieve WhatsApp messages.
 */
class Messages {
    constructor(_options) {
        this._options = _options;
    }
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ
     *
     * Returns a paginated list of messages for the authenticated user. Supports filtering by `status`, `simId`, and free-text `search`. Results are ordered by creation date (most recent first). Use `page` (default 1) and `limit` (1–100, default 20) to paginate.
     *
     * @param {UnlimitedMessagingApi.MessageFindAllRequest} request
     * @param {Messages.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link UnlimitedMessagingApi.BadRequestError}
     * @throws {@link UnlimitedMessagingApi.UnauthorizedError}
     * @throws {@link UnlimitedMessagingApi.ForbiddenError}
     *
     * @example
     *     await client.messages.messageFindAll()
     */
    messageFindAll(request = {}, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__messageFindAll(request, requestOptions));
    }
    __messageFindAll() {
        return __awaiter(this, arguments, void 0, function* (request = {}, requestOptions) {
            var _a, _b;
            const { page, limit, channel, status, direction, simId, search } = request;
            const _queryParams = {};
            if (page != null) {
                _queryParams["page"] = page.toString();
            }
            if (limit != null) {
                _queryParams["limit"] = limit.toString();
            }
            if (channel != null) {
                _queryParams["channel"] = serializers.MessageFindAllRequestChannel.jsonOrThrow(channel, {
                    unrecognizedObjectKeys: "strip",
                });
            }
            if (status != null) {
                _queryParams["status"] = serializers.MessageFindAllRequestStatus.jsonOrThrow(status, {
                    unrecognizedObjectKeys: "strip",
                });
            }
            if (direction != null) {
                _queryParams["direction"] = serializers.MessageFindAllRequestDirection.jsonOrThrow(direction, {
                    unrecognizedObjectKeys: "strip",
                });
            }
            if (simId != null) {
                _queryParams["simId"] = simId;
            }
            if (search != null) {
                _queryParams["search"] = search;
            }
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.UnlimitedMessagingApiEnvironment.Production, "message"),
                method: "GET",
                headers: Object.assign({ Authorization: yield this._getAuthorizationHeader(), "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                queryParameters: _queryParams,
                requestType: "json",
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                withCredentials: true,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return {
                    data: serializers.MessageFindAllResponse.parseOrThrow(_response.body, {
                        unrecognizedObjectKeys: "passthrough",
                        allowUnrecognizedUnionMembers: true,
                        allowUnrecognizedEnumValues: true,
                        breadcrumbsPrefix: ["response"],
                    }),
                    rawResponse: _response.rawResponse,
                };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 400:
                        throw new UnlimitedMessagingApi.BadRequestError(_response.error.body, _response.rawResponse);
                    case 401:
                        throw new UnlimitedMessagingApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 403:
                        throw new UnlimitedMessagingApi.ForbiddenError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.UnlimitedMessagingApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.UnlimitedMessagingApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.UnlimitedMessagingApiTimeoutError("Timeout exceeded when calling GET /message.");
                case "unknown":
                    throw new errors.UnlimitedMessagingApiError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:WRITE
     *
     * Queues a WhatsApp message for delivery to the specified `recipient` phone number (E.164 format). If `simId` is omitted, the platform resolves a SIM automatically using this priority order: (1) if the caller has exactly one active SIM, it is used; (2) if the caller has no SIM, the shared system SIM is used as fallback; (3) if the caller has multiple active SIMs, a `400` is returned asking to specify `simId`. Returns `404` if no SIM is available at all. Message text is limited to 1 600 characters.
     *
     * @param {UnlimitedMessagingApi.MessageSendRequest} request
     * @param {Messages.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link UnlimitedMessagingApi.BadRequestError}
     * @throws {@link UnlimitedMessagingApi.UnauthorizedError}
     * @throws {@link UnlimitedMessagingApi.ForbiddenError}
     * @throws {@link UnlimitedMessagingApi.NotFoundError}
     * @throws {@link UnlimitedMessagingApi.UnprocessableEntityError}
     *
     * @example
     *     await client.messages.messageSend({
     *         recipient: "recipient",
     *         text: "text"
     *     })
     */
    messageSend(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__messageSend(request, requestOptions));
    }
    __messageSend(request, requestOptions) {
        return __awaiter(this, void 0, void 0, function* () {
            var _a, _b;
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.UnlimitedMessagingApiEnvironment.Production, "message"),
                method: "POST",
                headers: Object.assign({ Authorization: yield this._getAuthorizationHeader(), "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                requestType: "json",
                body: serializers.MessageSendRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                withCredentials: true,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return {
                    data: serializers.MessageSendResponse.parseOrThrow(_response.body, {
                        unrecognizedObjectKeys: "passthrough",
                        allowUnrecognizedUnionMembers: true,
                        allowUnrecognizedEnumValues: true,
                        breadcrumbsPrefix: ["response"],
                    }),
                    rawResponse: _response.rawResponse,
                };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 400:
                        throw new UnlimitedMessagingApi.BadRequestError(_response.error.body, _response.rawResponse);
                    case 401:
                        throw new UnlimitedMessagingApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 403:
                        throw new UnlimitedMessagingApi.ForbiddenError(_response.error.body, _response.rawResponse);
                    case 404:
                        throw new UnlimitedMessagingApi.NotFoundError(_response.error.body, _response.rawResponse);
                    case 422:
                        throw new UnlimitedMessagingApi.UnprocessableEntityError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.UnlimitedMessagingApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.UnlimitedMessagingApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.UnlimitedMessagingApiTimeoutError("Timeout exceeded when calling POST /message.");
                case "unknown":
                    throw new errors.UnlimitedMessagingApiError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ
     *
     * Returns a single message by its unique identifier. Returns 404 if the message is not found or does not belong to the authenticated user.
     *
     * @param {string} id
     * @param {UnlimitedMessagingApi.MessageFindOneRequest} request
     * @param {Messages.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link UnlimitedMessagingApi.UnauthorizedError}
     * @throws {@link UnlimitedMessagingApi.ForbiddenError}
     * @throws {@link UnlimitedMessagingApi.NotFoundError}
     *
     * @example
     *     await client.messages.messageFindOne("id")
     */
    messageFindOne(id, request = {}, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__messageFindOne(id, request, requestOptions));
    }
    __messageFindOne(id_1) {
        return __awaiter(this, arguments, void 0, function* (id, request = {}, requestOptions) {
            var _a, _b;
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.UnlimitedMessagingApiEnvironment.Production, `message/${encodeURIComponent(id)}`),
                method: "GET",
                headers: Object.assign({ Authorization: yield this._getAuthorizationHeader(), "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                requestType: "json",
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                withCredentials: true,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return {
                    data: serializers.MessageFindOneResponse.parseOrThrow(_response.body, {
                        unrecognizedObjectKeys: "passthrough",
                        allowUnrecognizedUnionMembers: true,
                        allowUnrecognizedEnumValues: true,
                        breadcrumbsPrefix: ["response"],
                    }),
                    rawResponse: _response.rawResponse,
                };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 401:
                        throw new UnlimitedMessagingApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 403:
                        throw new UnlimitedMessagingApi.ForbiddenError(_response.error.body, _response.rawResponse);
                    case 404:
                        throw new UnlimitedMessagingApi.NotFoundError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.UnlimitedMessagingApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.UnlimitedMessagingApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.UnlimitedMessagingApiTimeoutError("Timeout exceeded when calling GET /message/{id}.");
                case "unknown":
                    throw new errors.UnlimitedMessagingApiError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ
     *
     * Returns every recorded status event per channel for a message owned by the authenticated user, flagging which ones advanced the denormalized current status (out-of-order acks stay non-effective). Returns 404 if the message is not found or does not belong to the authenticated user.
     *
     * @param {string} id
     * @param {UnlimitedMessagingApi.MessageGetStatusHistoryRequest} request
     * @param {Messages.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link UnlimitedMessagingApi.UnauthorizedError}
     * @throws {@link UnlimitedMessagingApi.ForbiddenError}
     * @throws {@link UnlimitedMessagingApi.NotFoundError}
     *
     * @example
     *     await client.messages.messageGetStatusHistory("id")
     */
    messageGetStatusHistory(id, request = {}, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__messageGetStatusHistory(id, request, requestOptions));
    }
    __messageGetStatusHistory(id_1) {
        return __awaiter(this, arguments, void 0, function* (id, request = {}, requestOptions) {
            var _a, _b;
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.UnlimitedMessagingApiEnvironment.Production, `message/${encodeURIComponent(id)}/status-history`),
                method: "GET",
                headers: Object.assign({ Authorization: yield this._getAuthorizationHeader(), "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                requestType: "json",
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                withCredentials: true,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return {
                    data: serializers.MessageGetStatusHistoryResponse.parseOrThrow(_response.body, {
                        unrecognizedObjectKeys: "passthrough",
                        allowUnrecognizedUnionMembers: true,
                        allowUnrecognizedEnumValues: true,
                        breadcrumbsPrefix: ["response"],
                    }),
                    rawResponse: _response.rawResponse,
                };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 401:
                        throw new UnlimitedMessagingApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 403:
                        throw new UnlimitedMessagingApi.ForbiddenError(_response.error.body, _response.rawResponse);
                    case 404:
                        throw new UnlimitedMessagingApi.NotFoundError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.UnlimitedMessagingApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.UnlimitedMessagingApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.UnlimitedMessagingApiTimeoutError("Timeout exceeded when calling GET /message/{id}/status-history.");
                case "unknown":
                    throw new errors.UnlimitedMessagingApiError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    _getAuthorizationHeader() {
        return __awaiter(this, void 0, void 0, function* () {
            return `Bearer ${yield core.Supplier.get(this._options.token)}`;
        });
    }
}
exports.Messages = Messages;
