/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
import { ApiKeyListResponseItem } from "../types/ApiKeyListResponseItem";
export declare const Response: core.serialization.Schema<serializers.apiKeys.apiKeyList.Response.Raw, UnlimitedMessagingApi.ApiKeyListResponseItem[]>;
export declare namespace Response {
    type Raw = ApiKeyListResponseItem.Raw[];
}
