# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from .message_controller_find_one_response_direction import (
    MessageControllerFindOneResponseDirection,
)
import typing
import pydantic
from .message_controller_find_one_response_status import (
    MessageControllerFindOneResponseStatus,
)
import datetime as dt
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class MessageControllerFindOneResponse(UniversalBaseModel):
    id: str
    content: str
    direction: MessageControllerFindOneResponseDirection
    external_id: typing.Optional[str] = pydantic.Field(alias="externalId", default=None)
    interlocutor: str
    retry_count: int = pydantic.Field(alias="retryCount")
    sim_id: str = pydantic.Field(alias="simId")
    status: MessageControllerFindOneResponseStatus
    created_at: dt.datetime = pydantic.Field(alias="createdAt")
    updated_at: dt.datetime = pydantic.Field(alias="updatedAt")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
