# This file was auto-generated by Fern from our API Definition.

import typing

MessageFindOneResponseStatus = typing.Union[
    typing.Literal["PENDING", "SENDING", "SENT", "DELIVERED", "READ", "FAILED"],
    typing.Any,
]
