/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const UnlimitedMessagingApiEnvironment: {
    readonly Default: "https://api.unlimitedmessaging.app";
};
export type UnlimitedMessagingApiEnvironment = typeof UnlimitedMessagingApiEnvironment.Default;
