/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type MessageControllerFindAllResponseDataItemDirection = "IN" | "OUT";
export declare const MessageControllerFindAllResponseDataItemDirection: {
    readonly In: "IN";
    readonly Out: "OUT";
};
