/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type MessageControllerFindAllRequestStatus = "PENDING" | "SENDING" | "SENT" | "DELIVERED" | "READ" | "FAILED";
export declare const MessageControllerFindAllRequestStatus: {
    readonly Pending: "PENDING";
    readonly Sending: "SENDING";
    readonly Sent: "SENT";
    readonly Delivered: "DELIVERED";
    readonly Read: "READ";
    readonly Failed: "FAILED";
};
