"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessageControllerFindAllResponseDataItemDirection = void 0;
exports.MessageControllerFindAllResponseDataItemDirection = {
    In: "IN",
    Out: "OUT",
};
