/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type MessageControllerSendResponseDirection = "IN" | "OUT";
export declare const MessageControllerSendResponseDirection: {
    readonly In: "IN";
    readonly Out: "OUT";
};
