/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as UnlimitedMessagingApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const SimUpdateSimRequest: core.serialization.Schema<serializers.SimUpdateSimRequest.Raw, UnlimitedMessagingApi.SimUpdateSimRequest>;
export declare namespace SimUpdateSimRequest {
    interface Raw {
        name: string;
    }
}
