/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../index";
export interface WebhookEventMessageEditedDataChannel {
    type: UnlimitedMessagingApi.WebhookEventMessageEditedDataChannelType;
    account: UnlimitedMessagingApi.WebhookEventMessageEditedDataChannelAccount;
    conversation: UnlimitedMessagingApi.WebhookEventMessageEditedDataChannelConversation;
}
