/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type WebhookEventMessageStatusDataMessagePreviousStatus = "PENDING" | "SENDING" | "SENT" | "DELIVERED" | "READ" | "FAILED" | "UNDELIVERABLE";
export declare const WebhookEventMessageStatusDataMessagePreviousStatus: {
    readonly Pending: "PENDING";
    readonly Sending: "SENDING";
    readonly Sent: "SENT";
    readonly Delivered: "DELIVERED";
    readonly Read: "READ";
    readonly Failed: "FAILED";
    readonly Undeliverable: "UNDELIVERABLE";
};
