/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../index";
export interface WebhookEventMessageStatusDataChannel {
    type: UnlimitedMessagingApi.WebhookEventMessageStatusDataChannelType;
    account: UnlimitedMessagingApi.WebhookEventMessageStatusDataChannelAccount;
    conversation: UnlimitedMessagingApi.WebhookEventMessageStatusDataChannelConversation;
}
