/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type WebhookEventMessageEditedDataEditKind = "text" | "caption";
export declare const WebhookEventMessageEditedDataEditKind: {
    readonly Text: "text";
    readonly Caption: "caption";
};
