/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface WebhookEventMessageHistoryDataMessagesItemReplyTo {
    externalId: string;
    participant: string | null;
}
