/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type WebhookEventGroupUpdatedType = "group.updated";
export declare const WebhookEventGroupUpdatedType: {
    readonly GroupUpdated: "group.updated";
};
