/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../index";
export interface WebhookEventMessageHistoryData {
    syncType: string;
    chunkOrder: number;
    progress: number;
    isLatest: boolean;
    channel: UnlimitedMessagingApi.WebhookEventMessageHistoryDataChannel;
    messages: UnlimitedMessagingApi.WebhookEventMessageHistoryDataMessagesItem[];
}
