/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type WebhookEventMessageEditedType = "message.edited";
export declare const WebhookEventMessageEditedType: {
    readonly MessageEdited: "message.edited";
};
