/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../index";
export interface WebhookEventGroupUpdatedDataChannel {
    type: UnlimitedMessagingApi.WebhookEventGroupUpdatedDataChannelType;
    account: UnlimitedMessagingApi.WebhookEventGroupUpdatedDataChannelAccount;
}
