/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../index";
export interface WebhookEventMessageReceived {
    type: UnlimitedMessagingApi.WebhookEventMessageReceivedType;
    eventId: string;
    occurredAt: Date;
    data: UnlimitedMessagingApi.WebhookEventMessageReceivedData;
}
