/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type WebhookEventMessageHistoryDataChannelType = "WHATSAPP" | "SMS" | "EMAIL";
export declare const WebhookEventMessageHistoryDataChannelType: {
    readonly Whatsapp: "WHATSAPP";
    readonly Sms: "SMS";
    readonly Email: "EMAIL";
};
