/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../index";
export interface WebhookEventGroupUpdated {
    type: UnlimitedMessagingApi.WebhookEventGroupUpdatedType;
    eventId: string;
    occurredAt: Date;
    data: UnlimitedMessagingApi.WebhookEventGroupUpdatedData;
}
