/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../index";
export interface WebhookEventMessageDeletedDataChannel {
    type: UnlimitedMessagingApi.WebhookEventMessageDeletedDataChannelType;
    account: UnlimitedMessagingApi.WebhookEventMessageDeletedDataChannelAccount;
    conversation: UnlimitedMessagingApi.WebhookEventMessageDeletedDataChannelConversation;
}
