/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type WebhookEventMessageSelfSentType = "message.self_sent";
export declare const WebhookEventMessageSelfSentType: {
    readonly MessageSelfSent: "message.self_sent";
};
