/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface WebhookEventMessageSelfSentDataChannelConversation {
    id: string | null;
    isGroup: boolean;
    address: string | null;
    participants?: string[];
}
