/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../index";
export interface WebhookEventMessageHistoryDataChannel {
    type: UnlimitedMessagingApi.WebhookEventMessageHistoryDataChannelType;
    account: UnlimitedMessagingApi.WebhookEventMessageHistoryDataChannelAccount;
}
