/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type WebhookEventMessageDeletedType = "message.deleted";
export declare const WebhookEventMessageDeletedType: {
    readonly MessageDeleted: "message.deleted";
};
