/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../index";
export interface WebhookEventMessageSelfSentData {
    message: UnlimitedMessagingApi.WebhookEventMessageSelfSentDataMessage;
    channel: UnlimitedMessagingApi.WebhookEventMessageSelfSentDataChannel;
}
