/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../index";
export interface WebhookEventMessageEditedDataEdit {
    externalId: string;
    messageId: string | null;
    newContent: string | null;
    kind: UnlimitedMessagingApi.WebhookEventMessageEditedDataEditKind | null;
    error: UnlimitedMessagingApi.WebhookEventMessageEditedDataEditError | null;
    editedAt: Date;
    sender: string | null;
    senderId: string;
    participant: string | null;
    fromMe: boolean;
}
