/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface WebhookEventMessageDeletedDataDeletion {
    externalId: string;
    messageId: string | null;
    deletedAt: Date;
    deletedBy: string | null;
    deletedById: string;
    participant: string | null;
    fromMe: boolean;
}
