/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type WebhookEventMessageReceivedDataMessageDirection = "IN" | "OUT";
export declare const WebhookEventMessageReceivedDataMessageDirection: {
    readonly In: "IN";
    readonly Out: "OUT";
};
