/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
import { MessageFindAllResponseDataItem } from "./MessageFindAllResponseDataItem";
export declare const MessageFindAllResponse: core.serialization.ObjectSchema<serializers.MessageFindAllResponse.Raw, UnlimitedMessagingApi.MessageFindAllResponse>;
export declare namespace MessageFindAllResponse {
    interface Raw {
        data: MessageFindAllResponseDataItem.Raw[];
        total: number;
        page: number;
        limit: number;
        totalPages: number;
    }
}
