/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
import { MessageFindOneResponseDirection } from "./MessageFindOneResponseDirection";
import { MessageFindOneResponseStatus } from "./MessageFindOneResponseStatus";
export declare const MessageFindOneResponse: core.serialization.ObjectSchema<serializers.MessageFindOneResponse.Raw, UnlimitedMessagingApi.MessageFindOneResponse>;
export declare namespace MessageFindOneResponse {
    interface Raw {
        id: string;
        content: string;
        direction: MessageFindOneResponseDirection.Raw;
        externalId: string | null;
        interlocutor: string;
        retryCount: number;
        simId: string;
        status: MessageFindOneResponseStatus.Raw;
        createdAt: string;
        updatedAt: string;
    }
}
