/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
import { MessageControllerFindOneResponseDirection } from "./MessageControllerFindOneResponseDirection";
import { MessageControllerFindOneResponseStatus } from "./MessageControllerFindOneResponseStatus";
export declare const MessageControllerFindOneResponse: core.serialization.ObjectSchema<serializers.MessageControllerFindOneResponse.Raw, UnlimitedMessagingApi.MessageControllerFindOneResponse>;
export declare namespace MessageControllerFindOneResponse {
    interface Raw {
        id: string;
        content: string;
        direction: MessageControllerFindOneResponseDirection.Raw;
        externalId: string | null;
        interlocutor: string;
        retryCount: number;
        simId: string;
        status: MessageControllerFindOneResponseStatus.Raw;
        createdAt: string;
        updatedAt: string;
    }
}
