/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageFindAllRequestStatus: core.serialization.Schema<serializers.MessageFindAllRequestStatus.Raw, UnlimitedMessagingApi.MessageFindAllRequestStatus>;
export declare namespace MessageFindAllRequestStatus {
    type Raw = "PENDING" | "SENDING" | "SENT" | "DELIVERED" | "READ" | "FAILED";
}
