/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../../../index";
export interface AccountGetAccountResponse {
    id: string;
    channel: UnlimitedMessagingApi.AccountGetAccountResponseChannel;
    isSystem: boolean;
    status: UnlimitedMessagingApi.AccountGetAccountResponseStatus;
    phone: string | null;
    name: string | null;
    blockedUntil: Date | null;
    createdAt: Date;
    updatedAt: Date;
}
