/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type AccountLinkAccountRequestMode = "stable" | "beta";
export declare const AccountLinkAccountRequestMode: {
    readonly Stable: "stable";
    readonly Beta: "beta";
};
