/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../../../index";
export interface AccountGetAccountResponse {
    id: string;
    channel: UnlimitedMessagingApi.AccountGetAccountResponseChannel;
    /** Who provides the account: USER when you connected it with your own credentials, SYSTEM when UnlimitedMessaging provides it. */
    owner: UnlimitedMessagingApi.AccountGetAccountResponseOwner;
    /** Deprecated: use `owner` instead (true when owner is SYSTEM). */
    isSystem: boolean;
    status: UnlimitedMessagingApi.AccountGetAccountResponseStatus;
    phone: string | null;
    name: string | null;
    /** Your own reference for this account, as set at linking or with PATCH. */
    externalRef: string | null;
    blockedUntil: Date | null;
    /** Whether fetching a stored media also requires authenticating as its owner. */
    mediaUrlRequiresAuth: boolean;
    /** Whether the account's message history is stored and announced. */
    syncHistory: boolean;
    /** The pause this account keeps between two sends, in seconds. */
    sendIntervalSeconds: number;
    createdAt: Date;
    updatedAt: Date;
}
