/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface AccountGetGroupResponseMembersItem {
    /** The member's id on the channel: a phone-number JID when known, a LID when WhatsApp hides the number. */
    id: string;
    /** The member phone number in E.164 format, null when WhatsApp hides it (then `id` is the only identifier). */
    address: string | null;
    lid: string | null;
    displayName: string | null;
    isAdmin: boolean;
    isSuperAdmin: boolean;
}
