/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../../../index";
export interface AccountGetChallengeResponse {
    challenge: UnlimitedMessagingApi.AccountGetChallengeResponseChallenge | null;
}
