/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface AccountListGroupsResponseDataItem {
    /** The group id on the channel (a WhatsApp group JID, `...@g.us`). Pass it as `recipient` to POST /message to write to the group. */
    id: string;
    name: string;
    memberCount: number;
}
