"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccountGetAccountResponseOwner = void 0;
exports.AccountGetAccountResponseOwner = {
    User: "USER",
    System: "SYSTEM",
};
