/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../../../index";
export interface AccountListGroupsResponse {
    data: UnlimitedMessagingApi.AccountListGroupsResponseDataItem[];
}
