/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../../../../index";
/**
 * @example
 *     {
 *         url: "url",
 *         eventTypes: ["message.received"]
 *     }
 */
export interface WebhookEndpointCreateRequest {
    url: string;
    description?: string;
    eventTypes: UnlimitedMessagingApi.WebhookEndpointCreateRequestEventTypesItem[];
}
