/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as UnlimitedMessagingApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { WebhookEndpointUpdateRequestEventTypesItem } from "../../types/WebhookEndpointUpdateRequestEventTypesItem";
export declare const WebhookEndpointUpdateRequest: core.serialization.Schema<serializers.WebhookEndpointUpdateRequest.Raw, UnlimitedMessagingApi.WebhookEndpointUpdateRequest>;
export declare namespace WebhookEndpointUpdateRequest {
    interface Raw {
        url?: string | null;
        description?: (string | null) | null;
        enabled?: boolean | null;
        eventTypes?: WebhookEndpointUpdateRequestEventTypesItem.Raw[] | null;
    }
}
