/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         externalId: "externalId"
 *     }
 */
export interface AccountRequestHistoryRequest {
    /** The `externalId` of the oldest message you hold in the conversation: the messages before it are requested. */
    externalId: string;
    /** How many earlier messages to ask for, 1 to 50. */
    count?: number;
}
