/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../../../../index";
/**
 * @example
 *     {}
 */
export interface AccountLinkAccountRequest {
    mode?: UnlimitedMessagingApi.AccountLinkAccountRequestMode;
}
