# This file was auto-generated by Fern from our API Definition.

from ..core.client_wrapper import SyncClientWrapper
import typing
from ..core.request_options import RequestOptions
from .types.sim_controller_get_linked_sims_response_item import (
    SimControllerGetLinkedSimsResponseItem,
)
from ..core.pydantic_utilities import parse_obj_as
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper


class SimClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def sim_controller_get_linked_sims(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SimControllerGetLinkedSimsResponseItem]:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE

        No description provided

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SimControllerGetLinkedSimsResponseItem]


        Examples
        --------
        from unlimited_messaging import UnlimitedMessagingApi

        client = UnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )
        client.sim.sim_controller_get_linked_sims()
        """
        _response = self._client_wrapper.httpx_client.request(
            "sim",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.List[SimControllerGetLinkedSimsResponseItem],
                    parse_obj_as(
                        type_=typing.List[SimControllerGetLinkedSimsResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncSimClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def sim_controller_get_linked_sims(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SimControllerGetLinkedSimsResponseItem]:
        """
        **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ, OTHER:WRITE

        No description provided

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SimControllerGetLinkedSimsResponseItem]


        Examples
        --------
        import asyncio

        from unlimited_messaging import AsyncUnlimitedMessagingApi

        client = AsyncUnlimitedMessagingApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.sim.sim_controller_get_linked_sims()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "sim",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    typing.List[SimControllerGetLinkedSimsResponseItem],
                    parse_obj_as(
                        type_=typing.List[SimControllerGetLinkedSimsResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
