/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../../../index";
export interface MessageFindAllResponseDataItem {
    id: string;
    content: string;
    direction: UnlimitedMessagingApi.MessageFindAllResponseDataItemDirection;
    externalId: string | null;
    error: string | null;
    interlocutor: string;
    conversationId: string | null;
    isGroup: boolean;
    retryCount: number;
    messagingAccountId: string;
    status: UnlimitedMessagingApi.MessageFindAllResponseDataItemStatus;
    channel: UnlimitedMessagingApi.MessageFindAllResponseDataItemChannel;
    accountChannel: UnlimitedMessagingApi.MessageFindAllResponseDataItemAccountChannel;
    watermarked: boolean;
    createdAt: Date;
    updatedAt: Date;
}
