"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessageSendResponseAccountChannel = void 0;
exports.MessageSendResponseAccountChannel = {
    WhatsappBailyes: "WHATSAPP_BAILYES",
    Email: "EMAIL",
    Sms: "SMS",
    WhatsappWhatsmeow: "WHATSAPP_WHATSMEOW",
};
