/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface MessageSendRequestProductData {
    productId: string;
    title: string;
    description?: string;
    currencyCode: string;
    priceAmount1000: number;
    salePriceAmount1000?: number;
    retailerId?: string;
    url?: string;
    imageUrl?: string;
    businessOwnerJid: string;
    body?: string;
    footer?: string;
}
