/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * `transactional` (an invoice, a reminder) is sent before any `normal` message already waiting in the queue, so a bulk send does not delay it. The pause between two sends of an account still applies. Defaults to `normal`.
 */
export type MessageSendRequestPriority = "normal" | "transactional";
export declare const MessageSendRequestPriority: {
    readonly Normal: "normal";
    readonly Transactional: "transactional";
};
