/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type MessageSendResponseAccountChannel = "WHATSAPP_BAILYES" | "EMAIL" | "SMS" | "WHATSAPP_WHATSMEOW";
export declare const MessageSendResponseAccountChannel: {
    readonly WhatsappBailyes: "WHATSAPP_BAILYES";
    readonly Email: "EMAIL";
    readonly Sms: "SMS";
    readonly WhatsappWhatsmeow: "WHATSAPP_WHATSMEOW";
};
