"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessageSendResponseChannel = void 0;
exports.MessageSendResponseChannel = {
    Whatsapp: "WHATSAPP",
    Sms: "SMS",
    Email: "EMAIL",
};
