/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../../../index";
export interface MessageFindOneResponse {
    id: string;
    content: string;
    direction: UnlimitedMessagingApi.MessageFindOneResponseDirection;
    externalId: string | null;
    error: string | null;
    interlocutor: string;
    retryCount: number;
    simId: string;
    status: UnlimitedMessagingApi.MessageFindOneResponseStatus;
    channel: UnlimitedMessagingApi.MessageFindOneResponseChannel;
    watermarked: boolean;
    createdAt: Date;
    updatedAt: Date;
}
