/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type MessageSendRequestMediaType = "image" | "document" | "audio";
export declare const MessageSendRequestMediaType: {
    readonly Image: "image";
    readonly Document: "document";
    readonly Audio: "audio";
};
