/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type MessageFindAllRequestDirection = "IN" | "OUT";
export declare const MessageFindAllRequestDirection: {
    readonly In: "IN";
    readonly Out: "OUT";
};
