/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type MessageSendRequestChannelsItemChannel = "WHATSAPP" | "EMAIL";
export declare const MessageSendRequestChannelsItemChannel: {
    readonly Whatsapp: "WHATSAPP";
    readonly Email: "EMAIL";
};
