/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as UnlimitedMessagingApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const MessageControllerSendRequest: core.serialization.Schema<serializers.MessageControllerSendRequest.Raw, UnlimitedMessagingApi.MessageControllerSendRequest>;
export declare namespace MessageControllerSendRequest {
    interface Raw {
        recipient: string;
        text: string;
        simId?: string | null;
    }
}
