/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const AccountGetAccountResponseChannel: core.serialization.Schema<serializers.AccountGetAccountResponseChannel.Raw, UnlimitedMessagingApi.AccountGetAccountResponseChannel>;
export declare namespace AccountGetAccountResponseChannel {
    type Raw = "WHATSAPP_BAILYES" | "EMAIL" | "SMS" | "WHATSAPP_WHATSMEOW";
}
