/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
import { AccountGetChallengeResponseChallengeQr } from "./AccountGetChallengeResponseChallengeQr";
import { AccountGetChallengeResponseChallengeCode } from "./AccountGetChallengeResponseChallengeCode";
import { AccountGetChallengeResponseChallengeRedirect } from "./AccountGetChallengeResponseChallengeRedirect";
import { AccountGetChallengeResponseChallengeNone } from "./AccountGetChallengeResponseChallengeNone";
export declare const AccountGetChallengeResponseChallenge: core.serialization.Schema<serializers.AccountGetChallengeResponseChallenge.Raw, UnlimitedMessagingApi.AccountGetChallengeResponseChallenge>;
export declare namespace AccountGetChallengeResponseChallenge {
    type Raw = AccountGetChallengeResponseChallenge.Qr | AccountGetChallengeResponseChallenge.Code | AccountGetChallengeResponseChallenge.Redirect | AccountGetChallengeResponseChallenge.None;
    interface Qr extends AccountGetChallengeResponseChallengeQr.Raw {
        kind: "qr";
    }
    interface Code extends AccountGetChallengeResponseChallengeCode.Raw {
        kind: "code";
    }
    interface Redirect extends AccountGetChallengeResponseChallengeRedirect.Raw {
        kind: "redirect";
    }
    interface None extends AccountGetChallengeResponseChallengeNone.Raw {
        kind: "none";
    }
}
