/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
import { AccountListAccountsResponseItemChannel } from "./AccountListAccountsResponseItemChannel";
import { AccountListAccountsResponseItemOwner } from "./AccountListAccountsResponseItemOwner";
import { AccountListAccountsResponseItemStatus } from "./AccountListAccountsResponseItemStatus";
export declare const AccountListAccountsResponseItem: core.serialization.ObjectSchema<serializers.AccountListAccountsResponseItem.Raw, UnlimitedMessagingApi.AccountListAccountsResponseItem>;
export declare namespace AccountListAccountsResponseItem {
    interface Raw {
        id: string;
        channel: AccountListAccountsResponseItemChannel.Raw;
        owner: AccountListAccountsResponseItemOwner.Raw;
        isSystem: boolean;
        status: AccountListAccountsResponseItemStatus.Raw;
        phone: string | null;
        name: string | null;
        externalRef: string | null;
        blockedUntil: string | null;
        mediaUrlRequiresAuth: boolean;
        syncHistory: boolean;
        sendIntervalSeconds: number;
        createdAt: string;
        updatedAt: string;
    }
}
