/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const AccountGetChallengeResponseChallengeQr: core.serialization.ObjectSchema<serializers.AccountGetChallengeResponseChallengeQr.Raw, UnlimitedMessagingApi.AccountGetChallengeResponseChallengeQr>;
export declare namespace AccountGetChallengeResponseChallengeQr {
    interface Raw {
        data: string;
        expiresAt?: string | null;
    }
}
