/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "./environments";
import * as core from "./core";
import { Messages } from "./api/resources/messages/client/Client";
import { SiMs } from "./api/resources/siMs/client/Client";
import { ApiKeys } from "./api/resources/apiKeys/client/Client";
export declare namespace UnlimitedMessagingApiClient {
    interface Options {
        environment?: core.Supplier<environments.UnlimitedMessagingApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class UnlimitedMessagingApiClient {
    protected readonly _options: UnlimitedMessagingApiClient.Options;
    protected _messages: Messages | undefined;
    protected _siMs: SiMs | undefined;
    protected _apiKeys: ApiKeys | undefined;
    constructor(_options: UnlimitedMessagingApiClient.Options);
    get messages(): Messages;
    get siMs(): SiMs;
    get apiKeys(): ApiKeys;
}
