# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from .account_list_accounts_response_item_channel import (
    AccountListAccountsResponseItemChannel,
)
from .account_list_accounts_response_item_owner import (
    AccountListAccountsResponseItemOwner,
)
import pydantic
from .account_list_accounts_response_item_status import (
    AccountListAccountsResponseItemStatus,
)
import typing
import datetime as dt
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class AccountListAccountsResponseItem(UniversalBaseModel):
    id: str
    channel: AccountListAccountsResponseItemChannel
    owner: AccountListAccountsResponseItemOwner = pydantic.Field()
    """
    Who provides the account: USER when you connected it with your own credentials, SYSTEM when UnlimitedMessaging provides it.
    """

    is_system: bool = pydantic.Field(alias="isSystem")
    """
    Deprecated: use `owner` instead (true when owner is SYSTEM).
    """

    status: AccountListAccountsResponseItemStatus
    phone: typing.Optional[str] = None
    name: typing.Optional[str] = None
    external_ref: typing.Optional[str] = pydantic.Field(
        alias="externalRef", default=None
    )
    """
    Your own reference for this account, as set at linking or with PATCH.
    """

    blocked_until: typing.Optional[dt.datetime] = pydantic.Field(
        alias="blockedUntil", default=None
    )
    media_url_requires_auth: bool = pydantic.Field(alias="mediaUrlRequiresAuth")
    """
    Whether fetching a stored media also requires authenticating as its owner.
    """

    sync_history: bool = pydantic.Field(alias="syncHistory")
    """
    Whether the account's message history is stored and announced.
    """

    send_interval_seconds: float = pydantic.Field(alias="sendIntervalSeconds")
    """
    The pause this account keeps between two sends, in seconds.
    """

    created_at: dt.datetime = pydantic.Field(alias="createdAt")
    updated_at: dt.datetime = pydantic.Field(alias="updatedAt")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
