# This file was auto-generated by Fern from our API Definition.

import typing

AccountGetAccountResponseStatus = typing.Union[
    typing.Literal["PENDING", "ACTIVE", "INACTIVE", "LINKING", "BLOCKED", "DUPLICATE"],
    typing.Any,
]
