# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .account_list_groups_response_data_item import AccountListGroupsResponseDataItem
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class AccountListGroupsResponse(UniversalBaseModel):
    data: typing.List[AccountListGroupsResponseDataItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
