# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations
from ...core.pydantic_utilities import UniversalBaseModel
import typing
import datetime as dt
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class AccountGetChallengeResponseChallenge_Qr(UniversalBaseModel):
    kind: typing.Literal["qr"] = "qr"
    data: str
    expires_at: typing.Optional[dt.datetime] = pydantic.Field(
        alias="expiresAt", default=None
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AccountGetChallengeResponseChallenge_Code(UniversalBaseModel):
    kind: typing.Literal["code"] = "code"
    data: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AccountGetChallengeResponseChallenge_Redirect(UniversalBaseModel):
    kind: typing.Literal["redirect"] = "redirect"
    url: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AccountGetChallengeResponseChallenge_None(UniversalBaseModel):
    kind: typing.Literal["none"] = "none"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


AccountGetChallengeResponseChallenge = typing.Union[
    AccountGetChallengeResponseChallenge_Qr,
    AccountGetChallengeResponseChallenge_Code,
    AccountGetChallengeResponseChallenge_Redirect,
    AccountGetChallengeResponseChallenge_None,
]
