# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class AccountListGroupsResponseDataItem(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The group id on the channel (a WhatsApp group JID, `...@g.us`). Pass it as `recipient` to POST /message to write to the group.
    """

    name: str
    member_count: int = pydantic.Field(alias="memberCount")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
