"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessageControllerFindAllResponseDataItemStatus = void 0;
exports.MessageControllerFindAllResponseDataItemStatus = {
    Pending: "PENDING",
    Sending: "SENDING",
    Sent: "SENT",
    Delivered: "DELIVERED",
    Read: "READ",
    Failed: "FAILED",
};
