/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const WebhookEndpointCreateRequestEventTypesItem: core.serialization.Schema<serializers.WebhookEndpointCreateRequestEventTypesItem.Raw, UnlimitedMessagingApi.WebhookEndpointCreateRequestEventTypesItem>;
export declare namespace WebhookEndpointCreateRequestEventTypesItem {
    type Raw = "message.received";
}
