/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const WebhookEndpointUpdateResponseEventTypesItem: core.serialization.Schema<serializers.WebhookEndpointUpdateResponseEventTypesItem.Raw, UnlimitedMessagingApi.WebhookEndpointUpdateResponseEventTypesItem>;
export declare namespace WebhookEndpointUpdateResponseEventTypesItem {
    type Raw = "message.received";
}
