/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as UnlimitedMessagingApi from "../../../index";
export declare namespace Message {
    interface Options {
        environment?: core.Supplier<environments.UnlimitedMessagingApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Message {
    protected readonly _options: Message.Options;
    constructor(_options: Message.Options);
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ
     *
     * No description provided
     *
     * @param {UnlimitedMessagingApi.MessageFindAllRequest} request
     * @param {Message.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.message.findAll({
     *         page: 1,
     *         limit: 1
     *     })
     */
    findAll(request: UnlimitedMessagingApi.MessageFindAllRequest, requestOptions?: Message.RequestOptions): core.HttpResponsePromise<UnlimitedMessagingApi.MessageFindAllResponse>;
    private __findAll;
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:WRITE
     *
     * No description provided
     *
     * @param {UnlimitedMessagingApi.MessageSendRequest} request
     * @param {Message.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.message.send({
     *         recipient: "recipient",
     *         text: "text"
     *     })
     */
    send(request: UnlimitedMessagingApi.MessageSendRequest, requestOptions?: Message.RequestOptions): core.HttpResponsePromise<UnlimitedMessagingApi.MessageSendResponse>;
    private __send;
    /**
     * **Protection**: Protected endpoint. Allowed roles: USER, ADMIN. Required scopes: OTHER:READ
     *
     * No description provided
     *
     * @param {string} id
     * @param {UnlimitedMessagingApi.MessageFindOneRequest} request
     * @param {Message.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.message.findOne("id")
     */
    findOne(id: string, request?: UnlimitedMessagingApi.MessageFindOneRequest, requestOptions?: Message.RequestOptions): core.HttpResponsePromise<UnlimitedMessagingApi.MessageFindOneResponse>;
    private __findOne;
    protected _getAuthorizationHeader(): Promise<string>;
}
