# This file was auto-generated by Fern from our API Definition.

import typing

SimGetLinkedSimsResponseItemStatus = typing.Union[
    typing.Literal["ACTIVE", "INACTIVE", "LINKING", "DUPLICATE_PHONE", "BLOCKED"],
    typing.Any,
]
