# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from .sim_get_sim_response_type import SimGetSimResponseType
from .sim_get_sim_response_status import SimGetSimResponseStatus
import typing
import datetime as dt
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class SimGetSimResponse(UniversalBaseModel):
    id: str
    type: SimGetSimResponseType
    status: SimGetSimResponseStatus
    phone: typing.Optional[str] = None
    name: typing.Optional[str] = None
    blocked_until: typing.Optional[dt.datetime] = pydantic.Field(
        alias="blockedUntil", default=None
    )
    created_at: dt.datetime = pydantic.Field(alias="createdAt")
    updated_at: dt.datetime = pydantic.Field(alias="updatedAt")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
