/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const SimGetLinkedSimsResponseItem: core.serialization.ObjectSchema<serializers.SimGetLinkedSimsResponseItem.Raw, UnlimitedMessagingApi.SimGetLinkedSimsResponseItem>;
export declare namespace SimGetLinkedSimsResponseItem {
    interface Raw {
        id: string;
        phone: string | null;
        name: string | null;
        createdAt: string;
        updatedAt: string;
    }
}
