"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimLegacyGetLinkedSimsResponseItemStatus = void 0;
exports.SimLegacyGetLinkedSimsResponseItemStatus = {
    Pending: "PENDING",
    Active: "ACTIVE",
    Inactive: "INACTIVE",
    Linking: "LINKING",
    Blocked: "BLOCKED",
    Duplicate: "DUPLICATE",
};
