/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type SimLegacyUpdateSimResponseType = "SYSTEM" | "USER";
export declare const SimLegacyUpdateSimResponseType: {
    readonly System: "SYSTEM";
    readonly User: "USER";
};
