/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type SimLegacyGetSimResponseStatus = "PENDING" | "ACTIVE" | "INACTIVE" | "LINKING" | "BLOCKED" | "DUPLICATE";
export declare const SimLegacyGetSimResponseStatus: {
    readonly Pending: "PENDING";
    readonly Active: "ACTIVE";
    readonly Inactive: "INACTIVE";
    readonly Linking: "LINKING";
    readonly Blocked: "BLOCKED";
    readonly Duplicate: "DUPLICATE";
};
