/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../../../index";
export interface SimLegacyUpdateSimResponse {
    id: string;
    type: UnlimitedMessagingApi.SimLegacyUpdateSimResponseType;
    channel: UnlimitedMessagingApi.SimLegacyUpdateSimResponseChannel;
    isSystem: boolean;
    status: UnlimitedMessagingApi.SimLegacyUpdateSimResponseStatus;
    phone: string | null;
    name: string | null;
    blockedUntil: Date | null;
    createdAt: Date;
    updatedAt: Date;
}
