# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .webhook_endpoint_list_response_data_item import (
    WebhookEndpointListResponseDataItem,
)
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class WebhookEndpointListResponse(UniversalBaseModel):
    data: typing.List[WebhookEndpointListResponseDataItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
