/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as UnlimitedMessagingApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const SimLegacyUpdateSimRequest: core.serialization.Schema<serializers.SimLegacyUpdateSimRequest.Raw, UnlimitedMessagingApi.SimLegacyUpdateSimRequest>;
export declare namespace SimLegacyUpdateSimRequest {
    interface Raw {
        name: string;
    }
}
