# This file was auto-generated by Fern from our API Definition.

from unlimited_messaging import UnlimitedMessagingApi
import os
import pytest
from unlimited_messaging import AsyncUnlimitedMessagingApi


@pytest.fixture
def client() -> UnlimitedMessagingApi:
    return UnlimitedMessagingApi(
        token=os.getenv("ENV_TOKEN", "token"),
        base_url=os.getenv("TESTS_BASE_URL", "base_url"),
    )


@pytest.fixture
def async_client() -> AsyncUnlimitedMessagingApi:
    return AsyncUnlimitedMessagingApi(
        token=os.getenv("ENV_TOKEN", "token"),
        base_url=os.getenv("TESTS_BASE_URL", "base_url"),
    )
