# This file was auto-generated by Fern from our API Definition.

from unlimited_messaging import UnlimitedMessagingApi
from unlimited_messaging import AsyncUnlimitedMessagingApi
import typing
from .utilities import validate_response


async def test_account_list_accounts(
    client: UnlimitedMessagingApi, async_client: AsyncUnlimitedMessagingApi
) -> None:
    expected_response: typing.Any = [
        {
            "id": "id",
            "channel": "WHATSAPP_BAILYES",
            "isSystem": True,
            "status": "PENDING",
            "phone": "phone",
            "name": "name",
            "blockedUntil": "2024-01-15T09:30:00Z",
            "createdAt": "2024-01-15T09:30:00Z",
            "updatedAt": "2024-01-15T09:30:00Z",
        }
    ]
    expected_types: typing.Tuple[typing.Any, typing.Any] = (
        "list",
        {
            0: {
                "id": None,
                "channel": None,
                "isSystem": None,
                "status": None,
                "phone": None,
                "name": None,
                "blockedUntil": "datetime",
                "createdAt": "datetime",
                "updatedAt": "datetime",
            }
        },
    )
    response = client.accounts.account_list_accounts()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.accounts.account_list_accounts()
    validate_response(async_response, expected_response, expected_types)


async def test_account_link_account(
    client: UnlimitedMessagingApi, async_client: AsyncUnlimitedMessagingApi
) -> None:
    expected_response: typing.Any = {"accountId": "accountId"}
    expected_types: typing.Any = {"accountId": None}
    response = client.accounts.account_link_account()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.accounts.account_link_account()
    validate_response(async_response, expected_response, expected_types)


async def test_account_get_challenge(
    client: UnlimitedMessagingApi, async_client: AsyncUnlimitedMessagingApi
) -> None:
    expected_response: typing.Any = {
        "challenge": {"data": "data", "expiresAt": "2024-01-15T09:30:00Z", "kind": "qr"}
    }
    expected_types: typing.Any = {"challenge": "no_validate"}
    response = client.accounts.account_get_challenge(account_id="accountId")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.accounts.account_get_challenge(
        account_id="accountId"
    )
    validate_response(async_response, expected_response, expected_types)


async def test_account_get_qr_code(
    client: UnlimitedMessagingApi, async_client: AsyncUnlimitedMessagingApi
) -> None:
    expected_response: typing.Any = {"qrCode": "qrCode"}
    expected_types: typing.Any = {"qrCode": None}
    response = client.accounts.account_get_qr_code(account_id="accountId")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.accounts.account_get_qr_code(
        account_id="accountId"
    )
    validate_response(async_response, expected_response, expected_types)


async def test_account_get_account(
    client: UnlimitedMessagingApi, async_client: AsyncUnlimitedMessagingApi
) -> None:
    expected_response: typing.Any = {
        "id": "id",
        "channel": "WHATSAPP_BAILYES",
        "isSystem": True,
        "status": "PENDING",
        "phone": "phone",
        "name": "name",
        "blockedUntil": "2024-01-15T09:30:00Z",
        "createdAt": "2024-01-15T09:30:00Z",
        "updatedAt": "2024-01-15T09:30:00Z",
    }
    expected_types: typing.Any = {
        "id": None,
        "channel": None,
        "isSystem": None,
        "status": None,
        "phone": None,
        "name": None,
        "blockedUntil": "datetime",
        "createdAt": "datetime",
        "updatedAt": "datetime",
    }
    response = client.accounts.account_get_account(account_id="accountId")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.accounts.account_get_account(
        account_id="accountId"
    )
    validate_response(async_response, expected_response, expected_types)


async def test_account_unlink_account(
    client: UnlimitedMessagingApi, async_client: AsyncUnlimitedMessagingApi
) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert (
        client.accounts.account_unlink_account(account_id="accountId")  # type: ignore[func-returns-value]
        is None
    )

    assert (
        await async_client.accounts.account_unlink_account(account_id="accountId")  # type: ignore[func-returns-value]
        is None
    )


async def test_account_update_account(
    client: UnlimitedMessagingApi, async_client: AsyncUnlimitedMessagingApi
) -> None:
    expected_response: typing.Any = {
        "id": "id",
        "channel": "WHATSAPP_BAILYES",
        "isSystem": True,
        "status": "PENDING",
        "phone": "phone",
        "name": "name",
        "blockedUntil": "2024-01-15T09:30:00Z",
        "createdAt": "2024-01-15T09:30:00Z",
        "updatedAt": "2024-01-15T09:30:00Z",
    }
    expected_types: typing.Any = {
        "id": None,
        "channel": None,
        "isSystem": None,
        "status": None,
        "phone": None,
        "name": None,
        "blockedUntil": "datetime",
        "createdAt": "datetime",
        "updatedAt": "datetime",
    }
    response = client.accounts.account_update_account(
        account_id="accountId", name="name"
    )
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.accounts.account_update_account(
        account_id="accountId", name="name"
    )
    validate_response(async_response, expected_response, expected_types)
