# This file was auto-generated by Fern from our API Definition.

from unlimited_messaging import UnlimitedMessagingApi
from unlimited_messaging import AsyncUnlimitedMessagingApi
import typing
from .utilities import validate_response


async def test_message_controller_find_all(
    client: UnlimitedMessagingApi, async_client: AsyncUnlimitedMessagingApi
) -> None:
    expected_response: typing.Any = {
        "data": [
            {
                "id": "id",
                "content": "content",
                "direction": "IN",
                "externalId": "externalId",
                "interlocutor": "interlocutor",
                "retryCount": 1,
                "simId": "simId",
                "status": "PENDING",
                "createdAt": "2024-01-15T09:30:00Z",
                "updatedAt": "2024-01-15T09:30:00Z",
            }
        ],
        "total": 1,
        "page": 1,
        "limit": 1,
        "totalPages": 1,
    }
    expected_types: typing.Any = {
        "data": (
            "list",
            {
                0: {
                    "id": None,
                    "content": None,
                    "direction": None,
                    "externalId": None,
                    "interlocutor": None,
                    "retryCount": "integer",
                    "simId": None,
                    "status": None,
                    "createdAt": "datetime",
                    "updatedAt": "datetime",
                }
            },
        ),
        "total": "integer",
        "page": "integer",
        "limit": "integer",
        "totalPages": "integer",
    }
    response = client.message.message_controller_find_all(page=1, limit=1)
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.message.message_controller_find_all(
        page=1, limit=1
    )
    validate_response(async_response, expected_response, expected_types)


async def test_message_controller_send(
    client: UnlimitedMessagingApi, async_client: AsyncUnlimitedMessagingApi
) -> None:
    expected_response: typing.Any = {
        "id": "id",
        "content": "content",
        "direction": "IN",
        "externalId": "externalId",
        "interlocutor": "interlocutor",
        "retryCount": 1,
        "simId": "simId",
        "status": "PENDING",
        "createdAt": "2024-01-15T09:30:00Z",
        "updatedAt": "2024-01-15T09:30:00Z",
    }
    expected_types: typing.Any = {
        "id": None,
        "content": None,
        "direction": None,
        "externalId": None,
        "interlocutor": None,
        "retryCount": "integer",
        "simId": None,
        "status": None,
        "createdAt": "datetime",
        "updatedAt": "datetime",
    }
    response = client.message.message_controller_send(
        recipient="recipient", text="text"
    )
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.message.message_controller_send(
        recipient="recipient", text="text"
    )
    validate_response(async_response, expected_response, expected_types)
