/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MediaUploadResponse: core.serialization.ObjectSchema<serializers.MediaUploadResponse.Raw, UnlimitedMessagingApi.MediaUploadResponse>;
export declare namespace MediaUploadResponse {
    interface Raw {
        url: string;
        mimeType: string;
        filename?: string | null;
    }
}
