/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const SimGetSimQrCodeResponse: core.serialization.ObjectSchema<serializers.SimGetSimQrCodeResponse.Raw, UnlimitedMessagingApi.SimGetSimQrCodeResponse>;
export declare namespace SimGetSimQrCodeResponse {
    interface Raw {
        qrCode: string | null;
    }
}
