/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const SimGetLinkedSimsResponseItemStatus: core.serialization.Schema<serializers.SimGetLinkedSimsResponseItemStatus.Raw, UnlimitedMessagingApi.SimGetLinkedSimsResponseItemStatus>;
export declare namespace SimGetLinkedSimsResponseItemStatus {
    type Raw = "ACTIVE" | "INACTIVE" | "LINKING" | "DUPLICATE_PHONE" | "BLOCKED";
}
