/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const SimLinkSimResponse: core.serialization.ObjectSchema<serializers.SimLinkSimResponse.Raw, UnlimitedMessagingApi.SimLinkSimResponse>;
export declare namespace SimLinkSimResponse {
    interface Raw {
        simId: string;
    }
}
