/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
import { SimUpdateSimResponseType } from "./SimUpdateSimResponseType";
import { SimUpdateSimResponseStatus } from "./SimUpdateSimResponseStatus";
export declare const SimUpdateSimResponse: core.serialization.ObjectSchema<serializers.SimUpdateSimResponse.Raw, UnlimitedMessagingApi.SimUpdateSimResponse>;
export declare namespace SimUpdateSimResponse {
    interface Raw {
        id: string;
        type: SimUpdateSimResponseType.Raw;
        status: SimUpdateSimResponseStatus.Raw;
        phone: string | null;
        name: string | null;
        blockedUntil: string | null;
        createdAt: string;
        updatedAt: string;
    }
}
