/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SimControllerGetLinkedSimsResponseItem {
    id: string;
    phone: string | null;
    createdAt: Date;
    updatedAt: Date;
}
