/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type SimControllerGetLinkedSimsResponseItemStatus = "ACTIVE" | "INACTIVE";
export declare const SimControllerGetLinkedSimsResponseItemStatus: {
    readonly Active: "ACTIVE";
    readonly Inactive: "INACTIVE";
};
