/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../../../index";
export interface SimControllerGetLinkedSimsResponseItem {
    id: string;
    phone: string | null;
    status: UnlimitedMessagingApi.SimControllerGetLinkedSimsResponseItemStatus;
    type: UnlimitedMessagingApi.SimControllerGetLinkedSimsResponseItemType;
    createdAt: Date;
    updatedAt: Date;
}
