# This file was auto-generated by Fern from our API Definition.

import typing

MessageSendResponseAccountChannel = typing.Union[
    typing.Literal["WHATSAPP_BAILYES", "EMAIL", "SMS", "WHATSAPP_WHATSMEOW"], typing.Any
]
