# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .message_get_status_history_response_channels_item import (
    MessageGetStatusHistoryResponseChannelsItem,
)
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class MessageGetStatusHistoryResponse(UniversalBaseModel):
    message_id: str = pydantic.Field(alias="messageId")
    channels: typing.List[MessageGetStatusHistoryResponseChannelsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
