# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from .message_find_all_response_data_item_direction import (
    MessageFindAllResponseDataItemDirection,
)
import typing
import pydantic
from .message_find_all_response_data_item_status import (
    MessageFindAllResponseDataItemStatus,
)
from .message_find_all_response_data_item_channel import (
    MessageFindAllResponseDataItemChannel,
)
from .message_find_all_response_data_item_account_channel import (
    MessageFindAllResponseDataItemAccountChannel,
)
import datetime as dt
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class MessageFindAllResponseDataItem(UniversalBaseModel):
    id: str
    content: str
    direction: MessageFindAllResponseDataItemDirection
    external_id: typing.Optional[str] = pydantic.Field(alias="externalId", default=None)
    error: typing.Optional[str] = None
    interlocutor: str
    conversation_id: typing.Optional[str] = pydantic.Field(
        alias="conversationId", default=None
    )
    is_group: bool = pydantic.Field(alias="isGroup")
    retry_count: int = pydantic.Field(alias="retryCount")
    messaging_account_id: str = pydantic.Field(alias="messagingAccountId")
    status: MessageFindAllResponseDataItemStatus
    channel: MessageFindAllResponseDataItemChannel
    account_channel: MessageFindAllResponseDataItemAccountChannel = pydantic.Field(
        alias="accountChannel"
    )
    watermarked: bool
    created_at: dt.datetime = pydantic.Field(alias="createdAt")
    updated_at: dt.datetime = pydantic.Field(alias="updatedAt")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
