# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import pydantic
from .message_get_status_history_response_channels_item_channel import (
    MessageGetStatusHistoryResponseChannelsItemChannel,
)
import typing
from .message_get_status_history_response_channels_item_events_item import (
    MessageGetStatusHistoryResponseChannelsItemEventsItem,
)
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class MessageGetStatusHistoryResponseChannelsItem(UniversalBaseModel):
    message_channel_id: str = pydantic.Field(alias="messageChannelId")
    channel: MessageGetStatusHistoryResponseChannelsItemChannel
    error: typing.Optional[str] = None
    events: typing.List[MessageGetStatusHistoryResponseChannelsItemEventsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
