# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class MessageFindAllResponseDataItemAttachmentsItem(UniversalBaseModel):
    url: str
    filename: typing.Optional[str] = None
    mime_type: str = pydantic.Field(alias="mimeType")
    size: int
    content_id: typing.Optional[str] = pydantic.Field(alias="contentId", default=None)
    """
    Set for an inline image the HTML body references as cid:<contentId>.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
