/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type SimGetLinkedSimsResponseItemStatus = "ACTIVE" | "INACTIVE" | "LINKING" | "DUPLICATE_PHONE" | "BLOCKED";
export declare const SimGetLinkedSimsResponseItemStatus: {
    readonly Active: "ACTIVE";
    readonly Inactive: "INACTIVE";
    readonly Linking: "LINKING";
    readonly DuplicatePhone: "DUPLICATE_PHONE";
    readonly Blocked: "BLOCKED";
};
