/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../../../index";
export interface SimUpdateSimResponse {
    id: string;
    type: UnlimitedMessagingApi.SimUpdateSimResponseType;
    status: UnlimitedMessagingApi.SimUpdateSimResponseStatus;
    phone: string | null;
    name: string | null;
    blockedUntil: Date | null;
    createdAt: Date;
    updatedAt: Date;
}
