"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimUpdateSimResponseType = void 0;
exports.SimUpdateSimResponseType = {
    System: "SYSTEM",
    User: "USER",
};
