/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         recipient: "recipient",
 *         text: "text"
 *     }
 */
export interface MessageControllerSendRequest {
    recipient: string;
    text: string;
    simId?: string;
}
