/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../../../../index";
/**
 * @example
 *     {}
 */
export interface MessageSendRequest {
    recipient?: string;
    text?: string;
    mediaUrl?: string;
    mediaType?: UnlimitedMessagingApi.MessageSendRequestMediaType;
    mimeType?: string;
    filename?: string;
    productData?: UnlimitedMessagingApi.MessageSendRequestProductData;
    accountId?: string | null;
    simId?: string | null;
    replyToMessageId?: string;
}
