/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as UnlimitedMessagingApi from "../../../../index";
/**
 * @example
 *     {}
 */
export interface MessageFindAllRequest {
    page?: number;
    limit?: number;
    channel?: UnlimitedMessagingApi.MessageFindAllRequestChannel;
    status?: UnlimitedMessagingApi.MessageFindAllRequestStatus;
    direction?: UnlimitedMessagingApi.MessageFindAllRequestDirection;
    simId?: string;
    search?: string;
}
