/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageSendRequestTo: core.serialization.ObjectSchema<serializers.MessageSendRequestTo.Raw, UnlimitedMessagingApi.MessageSendRequestTo>;
export declare namespace MessageSendRequestTo {
    interface Raw {
        phone?: string | null;
        email?: string | null;
    }
}
