/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageFindOneResponseAttachmentsItem: core.serialization.ObjectSchema<serializers.MessageFindOneResponseAttachmentsItem.Raw, UnlimitedMessagingApi.MessageFindOneResponseAttachmentsItem>;
export declare namespace MessageFindOneResponseAttachmentsItem {
    interface Raw {
        url: string;
        filename: string | null;
        mimeType: string;
        size: number;
        contentId: string | null;
    }
}
