/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageFindAllRequestChannel: core.serialization.Schema<serializers.MessageFindAllRequestChannel.Raw, UnlimitedMessagingApi.MessageFindAllRequestChannel>;
export declare namespace MessageFindAllRequestChannel {
    type Raw = "WHATSAPP" | "SMS" | "EMAIL";
}
