"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessageFindOneResponse = void 0;
const core = __importStar(require("../../../../core"));
const MessageFindOneResponseDirection_1 = require("./MessageFindOneResponseDirection");
const MessageFindOneResponseStatus_1 = require("./MessageFindOneResponseStatus");
const MessageFindOneResponseChannel_1 = require("./MessageFindOneResponseChannel");
const MessageFindOneResponseAccountChannel_1 = require("./MessageFindOneResponseAccountChannel");
exports.MessageFindOneResponse = core.serialization.object({
    id: core.serialization.string(),
    content: core.serialization.string().nullable(),
    direction: MessageFindOneResponseDirection_1.MessageFindOneResponseDirection,
    fromMe: core.serialization.boolean(),
    externalId: core.serialization.string().nullable(),
    error: core.serialization.string().nullable(),
    interlocutor: core.serialization.string(),
    conversationId: core.serialization.string().nullable(),
    isGroup: core.serialization.boolean(),
    replyToExternalId: core.serialization.string().nullable(),
    replyToParticipant: core.serialization.string().nullable(),
    retryCount: core.serialization.number(),
    messagingAccountId: core.serialization.string(),
    status: MessageFindOneResponseStatus_1.MessageFindOneResponseStatus,
    channel: MessageFindOneResponseChannel_1.MessageFindOneResponseChannel,
    accountChannel: MessageFindOneResponseAccountChannel_1.MessageFindOneResponseAccountChannel,
    watermarked: core.serialization.boolean(),
    mediaUrl: core.serialization.string().nullable(),
    mediaType: core.serialization.string().nullable(),
    mimeType: core.serialization.string().nullable(),
    mediaFilename: core.serialization.string().nullable(),
    productData: core.serialization.record(core.serialization.string(), core.serialization.unknown()).nullable(),
    createdAt: core.serialization.date(),
    updatedAt: core.serialization.date(),
});
