/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageSendRequestPriority: core.serialization.Schema<serializers.MessageSendRequestPriority.Raw, UnlimitedMessagingApi.MessageSendRequestPriority>;
export declare namespace MessageSendRequestPriority {
    type Raw = "normal" | "transactional";
}
