/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
import { MessageGetStatusHistoryResponseChannelsItemEventsItemStatus } from "./MessageGetStatusHistoryResponseChannelsItemEventsItemStatus";
export declare const MessageGetStatusHistoryResponseChannelsItemEventsItem: core.serialization.ObjectSchema<serializers.MessageGetStatusHistoryResponseChannelsItemEventsItem.Raw, UnlimitedMessagingApi.MessageGetStatusHistoryResponseChannelsItemEventsItem>;
export declare namespace MessageGetStatusHistoryResponseChannelsItemEventsItem {
    interface Raw {
        id: string;
        status: MessageGetStatusHistoryResponseChannelsItemEventsItemStatus.Raw;
        createdAt: string;
    }
}
