/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageFindAllResponseDataItemDirection: core.serialization.Schema<serializers.MessageFindAllResponseDataItemDirection.Raw, UnlimitedMessagingApi.MessageFindAllResponseDataItemDirection>;
export declare namespace MessageFindAllResponseDataItemDirection {
    type Raw = "IN" | "OUT";
}
