/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
import { MessageFindAllResponseDataItemDirection } from "./MessageFindAllResponseDataItemDirection";
import { MessageFindAllResponseDataItemStatus } from "./MessageFindAllResponseDataItemStatus";
import { MessageFindAllResponseDataItemChannel } from "./MessageFindAllResponseDataItemChannel";
export declare const MessageFindAllResponseDataItem: core.serialization.ObjectSchema<serializers.MessageFindAllResponseDataItem.Raw, UnlimitedMessagingApi.MessageFindAllResponseDataItem>;
export declare namespace MessageFindAllResponseDataItem {
    interface Raw {
        id: string;
        content: string;
        direction: MessageFindAllResponseDataItemDirection.Raw;
        externalId: string | null;
        error: string | null;
        interlocutor: string;
        retryCount: number;
        simId: string;
        status: MessageFindAllResponseDataItemStatus.Raw;
        channel: MessageFindAllResponseDataItemChannel.Raw;
        watermarked: boolean;
        createdAt: string;
        updatedAt: string;
    }
}
