/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
import { MessageFindOneResponseDirection } from "./MessageFindOneResponseDirection";
import { MessageFindOneResponseStatus } from "./MessageFindOneResponseStatus";
import { MessageFindOneResponseChannel } from "./MessageFindOneResponseChannel";
import { MessageFindOneResponseAccountChannel } from "./MessageFindOneResponseAccountChannel";
import { MessageFindOneResponseAttachmentsItem } from "./MessageFindOneResponseAttachmentsItem";
export declare const MessageFindOneResponse: core.serialization.ObjectSchema<serializers.MessageFindOneResponse.Raw, UnlimitedMessagingApi.MessageFindOneResponse>;
export declare namespace MessageFindOneResponse {
    interface Raw {
        id: string;
        content: string | null;
        direction: MessageFindOneResponseDirection.Raw;
        fromMe: boolean;
        externalId: string | null;
        error: string | null;
        interlocutor: string;
        conversationId: string | null;
        isGroup: boolean;
        replyToExternalId: string | null;
        replyToParticipant: string | null;
        retryCount: number;
        messagingAccountId: string;
        status: MessageFindOneResponseStatus.Raw;
        channel: MessageFindOneResponseChannel.Raw;
        accountChannel: MessageFindOneResponseAccountChannel.Raw;
        watermarked: boolean;
        subject: string | null;
        contentHtml: string | null;
        dispatchId: string | null;
        attachments: MessageFindOneResponseAttachmentsItem.Raw[];
        mediaUrl: string | null;
        mediaType: string | null;
        mimeType: string | null;
        mediaFilename: string | null;
        transcript: string | null;
        productData: Record<string, unknown> | null;
        sentAt: string | null;
        deletedAt: string | null;
        createdAt: string;
        updatedAt: string;
    }
}
