/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageSendRequestAttachmentsItem: core.serialization.ObjectSchema<serializers.MessageSendRequestAttachmentsItem.Raw, UnlimitedMessagingApi.MessageSendRequestAttachmentsItem>;
export declare namespace MessageSendRequestAttachmentsItem {
    interface Raw {
        url: string;
        filename?: string | null;
        mimeType?: string | null;
        contentId?: string | null;
    }
}
