/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageSendResponseAccountChannel: core.serialization.Schema<serializers.MessageSendResponseAccountChannel.Raw, UnlimitedMessagingApi.MessageSendResponseAccountChannel>;
export declare namespace MessageSendResponseAccountChannel {
    type Raw = "WHATSAPP_BAILYES" | "EMAIL" | "SMS" | "WHATSAPP_WHATSMEOW";
}
