/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageFindOneResponseAccountChannel: core.serialization.Schema<serializers.MessageFindOneResponseAccountChannel.Raw, UnlimitedMessagingApi.MessageFindOneResponseAccountChannel>;
export declare namespace MessageFindOneResponseAccountChannel {
    type Raw = "WHATSAPP_BAILYES" | "EMAIL" | "SMS" | "WHATSAPP_WHATSMEOW";
}
