/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
import { MessageSendResponseDirection } from "./MessageSendResponseDirection";
import { MessageSendResponseStatus } from "./MessageSendResponseStatus";
import { MessageSendResponseChannel } from "./MessageSendResponseChannel";
import { MessageSendResponseAccountChannel } from "./MessageSendResponseAccountChannel";
import { MessageSendResponseAttachmentsItem } from "./MessageSendResponseAttachmentsItem";
import { MessageSendResponseMessagesItem } from "./MessageSendResponseMessagesItem";
export declare const MessageSendResponse: core.serialization.ObjectSchema<serializers.MessageSendResponse.Raw, UnlimitedMessagingApi.MessageSendResponse>;
export declare namespace MessageSendResponse {
    interface Raw {
        id: string;
        content: string | null;
        direction: MessageSendResponseDirection.Raw;
        fromMe: boolean;
        externalId: string | null;
        error: string | null;
        interlocutor: string;
        conversationId: string | null;
        isGroup: boolean;
        replyToExternalId: string | null;
        replyToParticipant: string | null;
        retryCount: number;
        messagingAccountId: string;
        status: MessageSendResponseStatus.Raw;
        channel: MessageSendResponseChannel.Raw;
        accountChannel: MessageSendResponseAccountChannel.Raw;
        watermarked: boolean;
        subject: string | null;
        contentHtml: string | null;
        dispatchId: string;
        attachments: MessageSendResponseAttachmentsItem.Raw[];
        mediaUrl: string | null;
        mediaType: string | null;
        mimeType: string | null;
        mediaFilename: string | null;
        transcript: string | null;
        productData: Record<string, unknown> | null;
        sentAt: string | null;
        deletedAt: string | null;
        createdAt: string;
        updatedAt: string;
        messages: MessageSendResponseMessagesItem.Raw[];
    }
}
