/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as UnlimitedMessagingApi from "../../../../api/index";
import * as core from "../../../../core";
import { MessageSendResponseDirection } from "./MessageSendResponseDirection";
import { MessageSendResponseStatus } from "./MessageSendResponseStatus";
import { MessageSendResponseChannel } from "./MessageSendResponseChannel";
import { MessageSendResponseAccountChannel } from "./MessageSendResponseAccountChannel";
export declare const MessageSendResponse: core.serialization.ObjectSchema<serializers.MessageSendResponse.Raw, UnlimitedMessagingApi.MessageSendResponse>;
export declare namespace MessageSendResponse {
    interface Raw {
        id: string;
        content: string;
        direction: MessageSendResponseDirection.Raw;
        externalId: string | null;
        error: string | null;
        interlocutor: string;
        conversationId: string | null;
        isGroup: boolean;
        retryCount: number;
        messagingAccountId: string;
        status: MessageSendResponseStatus.Raw;
        channel: MessageSendResponseChannel.Raw;
        accountChannel: MessageSendResponseAccountChannel.Raw;
        watermarked: boolean;
        createdAt: string;
        updatedAt: string;
    }
}
